### ISSUE TITLE
🐧 Moira ↔ v18.0.0

### ISSUE THREAD

**Issue by hellscyth142** [itchio/itch-compatibility-watchlist#10]
:rotating_light: game [Moira](https://onagrostudios.itch.io/moira-demo) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/0b629263e4b02a576690c130d4e2fbaa).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
(wrong executable is being launched, can be fixed by the game's developer using a manifest, or heuristics could be improved to penalize anything with `nacl_helper`)

**Comment by hellscyth142** [comment]
It doesn't even look like the right executable has been included.

**Comment by fasterthanlime** [comment]
I think `nw` is the right executable — I really dislike the way nw.js does things but.. I think that should launch it. I'll have to try on my Linux box tomorrow

**Comment by hellscyth142** [comment]
You called, nw is an executable.

**Comment by fasterthanlime** [comment]
Am releasing 18.1.0 now, will probably help with this https://github.com/itchio/itch/issues/768

**Comment by hellscyth142** [comment]
Thanks.

**Comment by fasterthanlime** [comment]
v18.1.2 launches the correct executable :)
