### ISSUE TITLE
🐧 Survius ↔ v23.4.1

### ISSUE THREAD

**Issue by Leon0824** [itchio/itch-compatibility-watchlist#1002]
:rotating_light: game [Survius](https://chaozz.itch.io/survius) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/ffe2aa22d947397b642d22bdd0860b3d).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Try `sudo apt-get install libglu1-mesa:i386` in a terminal.

(If it asks you to uninstall half the packages that are installed, don't!)

If you get other such errors, use https://packages.ubuntu.com to search which package has the library you're looking for.
