### ISSUE TITLE
🍎 VA-11 Hall-A ↔ v23.4.1

### ISSUE THREAD

**Issue by HolographicDoll** [itchio/itch-compatibility-watchlist#1003]
:rotating_light: game [VA-11 Hall-A](https://sukebangames.itch.io/valhalla-bar) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/61f543d25096e1575af45bf02a2eb58f).

:running: Any additional details can go here!

**Comment by HolographicDoll** [comment]
This turns out to have been related to an empty copy of the app being left over by a partially failed uninstall and reinstall. Closing issue.

**Comment by fasterthanlime** [comment]
> an empty copy of the app being left over by

By "the app" you mean VA-11 Hall-A right? I've been looking into similar issues, the next version of the itch client should be more resilient towards those.

**Comment by HolographicDoll** [comment]
Yes, that's what I meant.
