### ISSUE TITLE
🏁 Deceiver ↔ v23.4.1

### ISSUE THREAD

**Issue by etodd** [itchio/itch-compatibility-watchlist#1015]
:rotating_light: game [Deceiver](https://etodd.itch.io/deceiver) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e56a4360437f14f820ae8f9df7541fb6).

:running: Runs fine if I select "Show local files" and run the executable manually. I suspect something is going wrong with the process of installing the MSVC runtime.

**Comment by fasterthanlime** [comment]
Got VS2017 installed on that computer?

**Comment by etodd** [comment]
Yep. Is that a no-no?

**Comment by fasterthanlime** [comment]
> Yep. Is that a no-no?

Well, the 2015 runtime just will *not* install if VS2017 is installed, which is annoying. So that explains it. It's on my radar, I'll get a fix out soon.

**Comment by etodd** [comment]
Wow that's crazy. Not a huge priority though, if you've got VS installed you're kind of asking for this kind of junk. 😛

**Comment by etodd** [comment]
This works now!

**Comment by fasterthanlime** [comment]
Oh yeah I completely forgot about this ticket but I fixed the underlying issue a while ago iirc - it was some numeric exit code I wasn't expecting but added to the list since :)
