### ISSUE TITLE
🐧 Rise of Industry ↔ v23.4.1

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch-compatibility-watchlist#1025]
:rotating_light: game [Rise of Industry](https://dapperpenguinstudios.itch.io/rise-of-industry) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c59fba98137ecf2925dbd1f10affcfe7).

:running: Looks like they have too many executables. There's two 32bit executables and two 64bit

**Comment by fasterthanlime** [comment]
Was the game installed earlier already?

I'm thinking it might have upgraded from a non-butler build to a butler build and the old version wasn't cleaned up properly.

Can you try uninstalling & installing the game again, see if it's still an issue?

**Comment by LiamDawe** [comment]
Yeah they've fixed it now.
