### ISSUE TITLE
🐧 Spelunky Classic HD ↔ v23.4.1

### ISSUE THREAD

**Issue by gmohre** [itchio/itch-compatibility-watchlist#1027]
:rotating_light: game [Spelunky Classic HD](https://yancharkin.itch.io/spelunky-classic-hd) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cf9ffa551f3cb6a5d8345f70eda79e70).

:running: Ubuntu 16.04/64-bit 
Initially tried running through command-line, tried through itch application, got this bug report feature!

**Comment by fasterthanlime** [comment]
Hey there!

Thanks for the report! I see you've already figured out which libs to install :)

In the future, the itch app may grab the required dependencies automatically, but for now it just warns you which are missing on launch.
