### ISSUE TITLE
🍎 Tales of Androgyny ↔ v23.4.1

### ISSUE THREAD

**Issue by HolographicDoll** [itchio/itch-compatibility-watchlist#1029]
:rotating_light: game [Tales of Androgyny](https://majalis.itch.io/tales-of-androgyny) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/63876678f9312fcf85ccdf3a1c631749).

:running: Any additional details can go here!

I think the executable is not getting unpacked correctly; the "local files" from the itch client consist of graphics and library files (one of which is the one that the client attempts to execute), but the direct download gives me a JAR in the folder structure (download location)/Tales of Androgyny Mac v0.1.20.0/Contents/Resourcer/TalesOfAndrogyny.jar (and that's what i can succesfully run).

**Comment by fasterthanlime** [comment]
Mh it looks like it's a .jar getting extracted, which shouldn't happen, I'll take a look.
