### ISSUE TITLE
🍎 Asset Forge Deluxe ↔ v23.4.1

### ISSUE THREAD

**Issue by WireDepp** [itchio/itch-compatibility-watchlist#1055]
:rotating_light: tool [Asset Forge Deluxe](https://kenney.itch.io/assetforge-deluxe) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/35f1eb545f54378ea9c4e43024d75086).

:running: Just updated to 1.2.0. tried to restart itch.io and my computer

**Comment by fasterthanlime** [comment]
Unfortunately a known issue: https://github.com/itchio/itch/issues/957 - please uninstall Asset Forge and install it again, and it'll start working again.

The next version of the app won't have that particular problem.

**Comment by fasterthanlime** [comment]
Good news - if you upgrade to itch v23.4.2 (User menu -> Check for updates), the problem will fix itself (without having to uninstall/re-install Asset Forge Deluxe.)
