### ISSUE TITLE
🍎 Asset Forge Deluxe ↔ v23.4.1

### ISSUE THREAD

**Issue by tthomas48** [itchio/itch-compatibility-watchlist#1056]
:rotating_light: tool [Asset Forge Deluxe](https://kenney.itch.io/assetforge-deluxe) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a7f8f93db27ef883a496d8ce63b56886).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Unfortunately you'll have to uninstall & install Asset Forge Deluxe after the v1.2.0 update - it's an app bug, the next version will fix that.
