### ISSUE TITLE
🐧 Ashworld ↔ v23.4.1

### ISSUE THREAD

**Issue by michael-nischt** [itchio/itch-compatibility-watchlist#1058]
:rotating_light: game [Ashworld](https://orangepixel.itch.io/ashworld) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/aa0c0f767cc77f577b44f73a72258fc0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like the game only ships a 32-bit executable (and you're running 64-bit linux).

The itch app tries to find a .jar to launch, but it doesn't look like it finds the right one.

**Comment by fasterthanlime** [comment]
I'd ask the developer for a Linux 64-bit build

**Comment by michael-nischt** [comment]
A 64bit would be ideal since 32bit is <0.5% for Linux users. 

Installing the following
`sudo apt install libxtst6:i386`
**and** running the game directly (not through the itch client) works for now.

**Comment by fasterthanlime** [comment]
> A 64bit would be ideal since 32bit is <0.5% for Linux users.

Oh, I agree with you very much.

> Installing the following
> sudo apt install libxtst6:i386
> and running the game directly (not through the itch client) works for now.

Cool. The jury's out on whether "the app trying to find the .jar if there's only a 32-bit executable on 64-bit linux" is really useful.

Whenever we add automatic dependency fetching for Linux games, it'll probably be time to remove it.

**Comment by fasterthanlime** [comment]
Ashworld now ships a 64-bit linux build, if you upgrade the game from the app it should work now!

https://twitter.com/fasterthanlime/status/887286960997494785
