### ISSUE TITLE
🏁 Noise Snke ↔ v18.6.2

### ISSUE THREAD

**Issue by CrillFactor** [itchio/itch-compatibility-watchlist#106]
:rotating_light: game [Noise Snke](https://andymakes.itch.io/noise-snke) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/8dabdaf9a1146b99e33c4e64957edc94).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like a game bug, please get in touch with the developer https://andymakes.itch.io/ !
