### ISSUE TITLE
🐧 Ashworld ↔ v23.4.2

### ISSUE THREAD

**Issue by argumento** [itchio/itch-compatibility-watchlist#1063]
:rotating_light: game [Ashworld](https://orangepixel.itch.io/ashworld) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/42901341a625df57c134ff618e91ec9a).

:running: Game fails to launch. I'm using ubuntu 16.04

**Comment by fasterthanlime** [comment]
Duplicate of #1058, unfortunately that game only ships a 32-bit version

**Comment by fasterthanlime** [comment]
Ashworld now ships a 64-bit linux build, if you upgrade the game from the app it should work now!

https://twitter.com/fasterthanlime/status/887286960997494785

**Comment by argumento** [comment]
Thanks. Now it runs perfectly.
