### ISSUE TITLE
🏁 Battle Ships ↔ v23.4.2

### ISSUE THREAD

**Issue by ShinySky42** [itchio/itch-compatibility-watchlist#1088]
:rotating_light: game [Battle Ships](https://ilovegameswow.itch.io/battle-ships) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/80dfa9a43c4a8c517f8e626599bef347).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
This doesn't look like a legitimate game - I've suspended the account.
