### ISSUE TITLE
🏁 Sprytile ↔ v23.4.2

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#1092]
:rotating_light: tool [Sprytile](https://chemikhazi.itch.io/sprytile) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5d3d997ac9da05f96175f923dc373008).

:running: Any additional details can go here!
sometimes when I downlaod an .exe file is says the file is missing and the file  hasn't been installed.

![image](https://user-images.githubusercontent.com/29752610/28748087-0840a89c-74a6-11e7-8ccf-735c355b8be8.png)

**Comment by fasterthanlime** [comment]
Yeah, that's a blender addon, not a standalone executable, the app doesn't know what to do with it :)
