### ISSUE TITLE
🐧 Space Jammers ↔ v18.1.2

### ISSUE THREAD

**Issue by michalwiking** [itchio/itch-compatibility-watchlist#11]
:rotating_light: game [Space Jammers](https://spreadshot.itch.io/space-jammers) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/21c011c8c2395057d5467a61b31c3ce6).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like you're missing openal.

However, the developer should ship those libraries with the game, feel free to point them to https://itch.io/docs/itch/integrating/platforms/linux.html !
