### ISSUE TITLE
🍎 Vampire of the Sands ↔ v23.0.0

### ISSUE THREAD

**Issue by djshire** [itchio/itch-compatibility-watchlist#1111]
:rotating_light: game [Vampire of the Sands](https://j.itch.io/vampire-of-the-sands) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a4dbcdd59a28c84e3185cab118cfaafc).

:running: Any additional details can go here!

Fails to launch, always mentions getting a Java JDK. Downloaded latest version of Java, still won't run.

**Comment by fasterthanlime** [comment]
Hey there!

You need a JRE, not a JDK (JDK's the part with the java compiler, you need the runtime)

Here's a direct link: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
