### ISSUE TITLE
🍎 The Light City of Karola ↔ v23.4.2

### ISSUE THREAD

**Issue by panchishin** [itchio/itch-compatibility-watchlist#1115]
:rotating_light: game [The Light City of Karola](https://davidcollado.itch.io/karola) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/741b4c4e5bf6d9589fe030efd295a311).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
It looks like your macOS version is too old to run this game:

```
Error -10825 is

"kLSIncompatibleSystemVersionErr = -10825, /* The app cannot run on the current OS version*/"
```

You may want to upgrade your macOS & try again!
