### ISSUE TITLE
🏁 Battlefleet Engineer ↔ v23.4.2

### ISSUE THREAD

**Issue by Metalfusion** [itchio/itch-compatibility-watchlist#1118]
:rotating_light: game [Battlefleet Engineer](https://metalfusion.itch.io/battlefleet-engineer) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3b30eff4c54badc644310493f5c6af4e).

:running: Any additional details can go here!

Seems like .net 4.5.2 prerequisite is broken.

**Comment by fasterthanlime** [comment]
Good catch, lemme take a look

**Comment by fasterthanlime** [comment]
@Metalfusion should be fixed, can you confirm it works now?

**Comment by Metalfusion** [comment]
Seems to work, thanks!
