### ISSUE TITLE
🐧 Last Wood ↔ v23.4.2

### ISSUE THREAD

**Issue by AngelODeath** [itchio/itch-compatibility-watchlist#1119]
:rotating_light: game [Last Wood](https://just-us.itch.io/last-wood) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b9685c93e666dc303e815ba47ee61b73).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
That's the wallpaper :)

There doesn't seem to be a Linux build for this game.
