### ISSUE TITLE
🏁 Snek ↔ v23.4.2

### ISSUE THREAD

**Issue by ItsSeaJay** [itchio/itch-compatibility-watchlist#1122]
:rotating_light: game [Snek](https://twisterge.itch.io/snek) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/aa8bf80fb6d38fad07150f23375102f1).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
You'll need a Java runtime to run Snek: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
