### ISSUE TITLE
🏁 She Plays Ultra High Definition Video Games ↔ v23.4.2

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#1125]
:rotating_light: game [She Plays Ultra High Definition Video Games](https://akssus.itch.io/spuhdvg) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cf602250616b55ea02bf4ec7f68d3edf).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Did you get it to run?
