### ISSUE TITLE
🍎 Tachyon ↔ v23.4.2

### ISSUE THREAD

**Issue by Veroaghe** [itchio/itch-compatibility-watchlist#1135]
:rotating_light: game [Tachyon](https://spektor.itch.io/tachyon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/81e17a5fcac7e5a48596e76fdf8d6c5b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
It looks like the version of Java on your mac is too old to run this game. You might need to install the latest from here: https://www.java.com/en/download/
