### ISSUE TITLE
🏁 MewnBase ↔ v23.4.2

### ISSUE THREAD

**Issue by triti** [itchio/itch-compatibility-watchlist#1136]
:rotating_light: game [MewnBase](https://cairn4.itch.io/mewnbase) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c53f63cb60ab785f9abff4d0872fb96f).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
It looks like there's an issue with your Java runtime. I'd download and install the latest JRE from https://www.java.com/en/download/index.jsp

**Comment by fasterthanlime** [comment]
Actually it looks like MewnBase ships its own JVM, so it's probably just a game bug / bad interaction with your computer, sorry about that. Please get in touch with the game's developer.
