### ISSUE TITLE
🐧 Crocotile 3D ↔ v23.4.1

### ISSUE THREAD

**Issue by JoshuaBehrens** [itchio/itch-compatibility-watchlist#1138]
:rotating_light: tool [Crocotile 3D](https://prominent.itch.io/crocotile3d) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/457ed677b903b74f13c47807e7bae252).

:running: I just started it. Two windows opened up and closed immediately.

**Comment by fasterthanlime** [comment]
Sounds like a Crocotile 3D bug, please get in touch with the developer: https://prominent.itch.io/ - you can include a link to this thread so they can take a look at the debug log!
