### ISSUE TITLE
🏁 Struggle Offensive ↔ v23.4.2

### ISSUE THREAD

**Issue by mesarth** [itchio/itch-compatibility-watchlist#1142]
:rotating_light: game [Struggle Offensive](https://rakarnov.itch.io/struggle-offensive) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e1f67eaeedce48b9f9517b21a60d6969).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
I've reached out to the developers to point the steps that can be taken to make the game compatible with the itch app: https://itch.io/post/265413
