### ISSUE TITLE
🏁 MewnBase ↔ v23.4.2

### ISSUE THREAD

**Issue by Olliebrown** [itchio/itch-compatibility-watchlist#1154]
:rotating_light: game [MewnBase](https://cairn4.itch.io/mewnbase) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/44811244b70984c03588b668a1c2f48c).

:running: Windows 10 x64, AMD Radeon R5 2.9ghz, embedded gfx

Just bought and tried to launch using the itch.io desktop. It fails to launch the JRE for some reason (see log) and cannot continue. It looks like you have the JRE distributed with the game but just in case, I tried installing the latest Java runtime and this did not help.

**Comment by fasterthanlime** [comment]
Please post directly to the game's community, at the bottom of this page: https://cairn4.itch.io/mewnbase - link this report so the developer can take a look at the debug log.

Thanks!

**Comment by Olliebrown** [comment]
Ahh sorry! I misinterpreted what the “report this problem” button was doing.  Sorry for the noise!
