### ISSUE TITLE
🐧 Poke Abby ↔ v23.4.2

### ISSUE THREAD

**Issue by GabrielCoelho** [itchio/itch-compatibility-watchlist#1156]
:rotating_light: game [Poke Abby](https://oxopotion.itch.io/poke-abby) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/670a074f986c7d6a6409bc9ab0b7a5e5).

:running: Any additional details can go here!

**Comment by GabrielCoelho** [comment]
anyone?

**Comment by fasterthanlime** [comment]
I often see SIGABRT in logs for Unity games on Linux but I've never been able to identify a root cause :(

You can try to hunt down the Unity logs (which are distinct), this page has the paths: https://docs.unity3d.com/Manual/LogFiles.html (look at the `Player` section).
