### ISSUE TITLE
🍎 Sewers & Streams ↔ v23.4.2

### ISSUE THREAD

**Issue by bdmorin** [itchio/itch-compatibility-watchlist#1158]
:rotating_light: game [Sewers & Streams](https://goblinairship.itch.io/sewers) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5b0abaa64775bb95900727a310e7a9e1).

:running: Any additional details can go here!

Loaded via Itch.io app
Haven't tried downloading and launching.
When launching via command line:
`
-> % open -a Sewers\ \&\ Streams
LSOpenURLsWithRole() failed for the application /Users/bdmorin/Library/Application Support/itch/apps/Sewers Streams/osx/Sewers & Streams.app with error -10810.
`

**Comment by fasterthanlime** [comment]
Well, 10810 is usually the missing executable bit on the binary inside the app bundle, but it's not that, since the log shows the app fixed it:

```
[2017-09-05 @ 12:09:16.404] [configure/common] Contents/MacOS/Sewers & Streams: is macExecutable, chmod +x
[2017-09-05 @ 12:09:16.409] [configure/common] Contents/Frameworks/MonoEmbedRuntime/osx/libMonoPosixHelper.dylib: is macExecutable, chmod +x
[2017-09-05 @ 12:09:16.415] [configure/common] Contents/Frameworks/MonoEmbedRuntime/osx/libmono.0.dylib: is macExecutable, chmod +x
```

I'd have to try out the game myself but you might want to contact the developer directly, there might just be something wrong with how the game's packaged!

**Comment by bdmorin** [comment]
heh.. I thought this was the developer. (=

```
 -> % ./MacOS/Sewers\ \&\ Streams
 2017-09-06 08:11:19.069 Sewers & Streams[95480:2158516] There was an error parsing the Info.plist for the bundle at URL <0x105900510>: NSCocoaErrorDomain - 3840
 2017-09-06 08:11:19.069 Sewers & Streams[95480:2158516] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting
```


I tried starting the executable directly. I'm not familiar with app bundling, so this is a mystery to me as well, I just wanted to report the bug. Happy to test fixes though.

**Comment by bdmorin** [comment]
I found this issue that matches my error..
https://github.com/resin-io/etcher/issues/1034

Only.. I'm not removing anything from /Library/Filesystems/ to test that theory. heh.

**Comment by fasterthanlime** [comment]
Yeah, the `Info.plist` file needs to exist, so it's definitely a packaging problem. You can leave a comment to the developer on the game's page: https://goblinairship.itch.io/sewers

Feel free to point them to this thread so they get all the info.

**Comment by almyu** [comment]
There is an `Info.plist`. My guess is that Unity didn't escape the `CFBundleExecutable` field correctly. @bdmorin, can you replace the `&` with `&amp;` in `Contents/Info.plist` and try running the app again? Thanks for bringing this up.

**Comment by bdmorin** [comment]
That did it! Works.

**Comment by fasterthanlime** [comment]
> My guess is that Unity didn't escape the CFBundleExecutable field correctly.

Oh, that makes a lot more sense. Sorry for doubting you! ⭐️

**Comment by almyu** [comment]
Sweet! I've updated the package. Thanks :heart:
