### ISSUE TITLE
🐧 Overland ↔ v23.4.2

### ISSUE THREAD

**Issue by krysgeka** [itchio/itch-compatibility-watchlist#1163]
:rotating_light: game [Overland](https://finji.itch.io/overland) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/40a84ae42b8991d82003d21d4807993c).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
SIGKILL doesn't sound like either an app or game bug, just the game being killed by you :)
