### ISSUE TITLE
🏁 Autonauts ↔ v23.4.2

### ISSUE THREAD

**Issue by Wolkas** [itchio/itch-compatibility-watchlist#1182]
:rotating_light: game [Autonauts](https://denki.itch.io/autonauts) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c1b1bc3f060b699e323e68fac53e559f).

:running: Any additional details can go here!

Whenever i update the game with the correct file it will not launch. If someone could please help me that would be great

**Comment by fasterthanlime** [comment]
Try installing the 'Win32' build instead of the 'Win64' one.

You'll need to uninstall the game first.
