### ISSUE TITLE
🏁 Overland ↔ v18.2.0

### ISSUE THREAD

**Issue by har0ld** [itchio/itch-compatibility-watchlist#12]
:rotating_light: game [Overland](https://finji.itch.io/overland) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9d8134dea68dc6c474a4a2b29465ef94).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
@har0ld when you click 'Show local files' and double-click Overland.exe yourself, does it launch?

**Comment by har0ld** [comment]
It did launch. Actually the first time was weird because it sent this bug but everything was fine.

Well, my character is dead and the game still wants me to play but that's another story :) Cheers!

**Comment by fasterthanlime** [comment]
> Well, my character is dead and the game still wants me to play but that's another story :) Cheers!

Haha, best of luck!

> It did launch. Actually the first time was weird because it sent this bug but everything was fine.

Oh, did it open the crash report thing _after_ the game exited normally?

**Comment by har0ld** [comment]
> Oh, did it open the crash report thing after the game exited normally?

Absolutely! I launched the 136 build through the Itch app and when I stopped playing it sent me directly to github for a bug report! So I submitted :)

**Comment by fasterthanlime** [comment]
The app now ignores games that exit with a non-zero code if they've been running for more than 10s (it just assumes you were able to play it). Closing!
