### ISSUE TITLE
🐧 Fruits of a Feather ↔ v23.4.2

### ISSUE THREAD

**Issue by cpoisson** [itchio/itch-compatibility-watchlist#1215]
:rotating_light: game [Fruits of a Feather](https://samuraipunk.itch.io/fruits-of-a-feather) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/605c46999923e6aae9687a2c3e7d57a7).

:running: Crash occurs when launching the game

**Comment by cpoisson** [comment]
Missing 32bits version of the library
Fixed by installing libxcursor-dev:i386 and libxrandr-dev:i386 
A SIGSEGV crash occurs when exiting the game tough...

**Comment by fasterthanlime** [comment]
> A SIGSEGV crash occurs when exiting the game tough...

That happens a lot with Unity games on Linux, I'm sure the Unity team is aware of it!
