### ISSUE TITLE
🏁 Autonauts ↔ v23.4.2

### ISSUE THREAD

**Issue by CobraA1** [itchio/itch-compatibility-watchlist#1237]
:rotating_light: game [Autonauts](https://denki.itch.io/autonauts) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/99ad9879e4ef973a19b6b076f1e469ae).

:running: Not sure what's up. But my PC has been having issues as of late, so I can't rule out that it's my PC.

**Comment by fasterthanlime** [comment]
I've never tried adding a OneDrive folder as an install location, so I'm not sure how it behaves.

`G:\OneDrive\~itch.io games\Autonauts\Autonauts.exe` is a strange path though!

**Comment by CobraA1** [comment]
So I moved it to a folder in my documents, and now Autonauts simply won't show as installed. Which is odd, because when I run it manually from the new folder it runs fine.

**Comment by CobraA1** [comment]
So I moved it to a folder in my documents, and now Autonauts simply won't show as installed. Which is odd, because when I run it manually from the new folder it runs fine.

. . . and I figured it out. It's my antivirus, sigh. My AV (Webroot) has been causing some major headaches recently, especially with the Fall Creator's update.
