### ISSUE TITLE
🍎 The Egg ↔ v23.4.2

### ISSUE THREAD

**Issue by Intel1146** [itchio/itch-compatibility-watchlist#1250]
:rotating_light: game [The Egg](https://lectronice.itch.io/the-egg) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/0c585a0ea4c76a19ded1c5b984bfd769).

**Comment by fasterthanlime** [comment]
It doesn't look like this game ships a Mac build, it's just tagged incorrectly :(
