### ISSUE TITLE
🏁 Enceladus ↔ v23.4.2

### ISSUE THREAD

**Issue by Jeffreyveggie** [itchio/itch-compatibility-watchlist#1251]
:rotating_light: game [Enceladus](https://plug-in-digital.itch.io/enceladus) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/ad492ce751ec171159128c2c7832a0a1).

:running: Any additional details can go here!

**Comment by Jeffreyveggie** [comment]
no Download

**Comment by fasterthanlime** [comment]
That's a steam-only game, the download is just a PDF telling you how to redeem your steam key.

**Comment by Jeffreyveggie** [comment]
wollte ohne steam
