### ISSUE TITLE
🏁 Directory ↔ v23.4.2

### ISSUE THREAD

**Issue by ynx0** [itchio/itch-compatibility-watchlist#1254]
:rotating_light: tool [Directory](https://joebrogers.itch.io/directoryapp) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e6c27db80e584a6cd613872e011c6b71).

:running: Any additional details can go here!
It says that there was not executable found.

**Comment by fasterthanlime** [comment]
Oh my, so this one is an .msi in a .rar file.

Looks like the developer was uploading the .msi directly earlier, but then went with the .rar ?

The developer of Directory can fix that by:

  * just uploading the .msi directly
  * uploading a .zip with the application (without installer) and a README etc.

You can use the app by just:

  * clicking `Show local files`
  * double-clicking the .msi file to install Directory
    * note that you won't be able to launch it via the itch app, since that'll install Directory outside of the app

**Comment by ynx0** [comment]
Ok thanks 👍
