### ISSUE TITLE
🏁 Computer Shop Sim ↔ v23.4.2

### ISSUE THREAD

**Issue by NarodGaming** [itchio/itch-compatibility-watchlist#1257]
:rotating_light: game [Computer Shop Sim](https://narodgaming.itch.io/comshopsim) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3ce9e15d8d20f85fb3530115ce360416).

:running: Totally unsure of what the problem is. I am the creator of the game and I thought to test out my game to make sure it works properly and this has been a problem for me.

**Comment by fasterthanlime** [comment]
Found the problem :)

butler checks for the return value `4294967287` when installing the DirectX redist - that value is larger than the maximum value a signed 32-bit integer can hold.

It worked just fine on 64-bit windows, where I did my tests, but not on 32-bit windows (which is the butler build the itch app installs by default).

I've changed the type of `code` to an unsigned 32-bit integer, which should work on both 32-bit and 64-bit. I'm releasing a new version of butler now (v9.0.0) - it should work for you after restarting the itch app!
