### ISSUE TITLE
🐧 Inside the Void ↔ v23.6.0

### ISSUE THREAD

**Issue by ask6155** [itchio/itch-compatibility-watchlist#1262]
:rotating_light: game [Inside the Void](https://3dmethods.itch.io/inside-the-void) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b3a67251e623f456b3eca3c539c02db3).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Can you post the contents of `/home/me/.config/unity3d/3DMethods/Inside the Void/Player.log` ?

**Comment by ask6155** [comment]
nvm I didn't had the required specs to run the game :(
