### ISSUE TITLE
🏁 I'd Cross the World for You ↔ v23.6.0

### ISSUE THREAD

**Issue by codyatwork** [itchio/itch-compatibility-watchlist#1268]
:rotating_light: game [I'd Cross the World for You](https://pklucky.itch.io/id-cross-the-world-for-you) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f7575b5d18ad95df8f0382948ade62e9).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like an unsupported installer type, I recommend reaching out to the developers of the game and pointing them to this page: https://itch.io/docs/itch/integrating/platforms/windows.html
