### ISSUE TITLE
🐧 Bit Pit ↔ v18.2.0

### ISSUE THREAD

**Issue by calexil** [itchio/itch-compatibility-watchlist#13]
:rotating_light: game [Bit Pit](https://logybit.itch.io/bitpit) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/55438fa0f2b96c65fa5c011eab5630e2).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Another 32-bit game.. what's the output of `uname -a` on your machine?

**Comment by calexil** [comment]
its 64 bit linux mint, but it worked fine on 17.3

im on 18 now, I enabled the 32 bit arch

```
  From: Amos Wenger <notifications@github.com>
```

 To: itchio/itch-compatibility-watchlist itch-compatibility-watchlist@noreply.github.com 
Cc: JD calexil@yahoo.com; Author author@noreply.github.com
 Sent: Friday, July 8, 2016 7:33 AM
 Subject: Re: [itchio/itch-compatibility-watchlist] 🐧 Bit Pit ↔ v18.2.0 (#13)

Another 32-bit game.. what's the output of uname -a on your machine? —

**Comment by fasterthanlime** [comment]
> its 64 bit linux mint, but it worked fine on 17.3

So launching that game (with 32-bit arch enabled) worked with 17.3 but not with 18? Does launching it manually work?

**Comment by calexil** [comment]
ill try tonight

```
  From: Amos Wenger <notifications@github.com>
```

 To: itchio/itch-compatibility-watchlist itch-compatibility-watchlist@noreply.github.com 
Cc: JD calexil@yahoo.com; Author author@noreply.github.com
 Sent: Friday, July 8, 2016 2:48 PM
 Subject: Re: [itchio/itch-compatibility-watchlist] 🐧 Bit Pit ↔ v18.2.0 (#13)

its 64 bit linux mint, but it worked fine on 17.3
So launching that game (with 32-bit arch enabled) worked with 17.3 but not with 18? Does launching it manually work?—

**Comment by calexil** [comment]
also, no directly launching the executable without the itch.io launcher did not work

**Comment by fasterthanlime** [comment]
the latest upload on bit pit is 204 days old, so I'm starting to suspect that something on your side broke!

**Comment by calexil** [comment]
"this game was last edited before 16.04 was even released... it's probably your fault..."

this statement makes no sense :p

```
  From: Amos Wenger <notifications@github.com>
```

 To: itchio/itch-compatibility-watchlist itch-compatibility-watchlist@noreply.github.com 
Cc: JD calexil@yahoo.com; Author author@noreply.github.com
 Sent: Friday, July 8, 2016 3:25 PM
 Subject: Re: [itchio/itch-compatibility-watchlist] 🐧 Bit Pit ↔ v18.2.0 (#13)

the latest upload on bit pit is 204 days old, so I'm starting to suspect that something on your side broke!—

**Comment by fasterthanlime** [comment]
I'm not saying it's your fault :) I'm saying: the game's developer didn't introduce breaking changes, neither did we (itch app) apparently, so apart from relaying that info to the dev, it's not a bug I can fix!

**Comment by calexil** [comment]
ah. ok well lets sort it out^^, this is agreat party game and I wanna get it runnin again.

**Comment by calexil** [comment]
It was working fine on fglrx, but thats depreciated in 16.04 so I had to use radeonSI to run it, does this game use something specific to proprietary drivers? Most itch.io games are built on unity but other unity games seem to be running fine

**Comment by fasterthanlime** [comment]
I just pointed to the developer to that thread, hopefully they can help!

**Comment by calexil** [comment]
ah gr8 thanks, ill do some further testing tonight

**Comment by calexil** [comment]
yay!, this issue was solved by adding the launch parameter '-force-opengl

perhaps it should launch with that by default?

**Comment by fasterthanlime** [comment]
Ah, I've heard of some Unity games having that problem. The problem is that forcing that launch parameter would probably break the game for others :/

But I do want to let users pass arguments to the games they launch using the app: https://github.com/itchio/itch/issues/366
