### ISSUE TITLE
🏁 Paramedium ↔ v23.6.0

### ISSUE THREAD

**Issue by dnielbloqg** [itchio/itch-compatibility-watchlist#1349]
:rotating_light: game [Paramedium](https://dinmoney.itch.io/paramedium) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cb1ed4e27797d7d92dbdf8ca93d47596).

:running: I tried downloading the game via Itch Launcher. It appears that the download contains only a folder with one .json file and 4 pictures. No executable found. Edit: It looks like those files are from one of the three files available when accessing the game site through a webbrowser. It's the Wallpaper file. The Launcher doesn't let me choose what file of those three to download.
![itch_2017-12-31_11-54-20](https://user-images.githubusercontent.com/34980975/34461069-60db1f06-ee21-11e7-8e68-0b44e89bbeea.png)
![explorer_2017-12-31_11-53-18](https://user-images.githubusercontent.com/34980975/34461070-640a0142-ee21-11e7-873c-c221a166199f.png)
![explorer_2017-12-31_11-53-14](https://user-images.githubusercontent.com/34980975/34461071-654dfd88-ee21-11e7-9182-a02859ceddde.png)

**Comment by fasterthanlime** [comment]
Yeah it looks like the Windows build of the game wasn't tagged properly, so it just installed the wallpaper pack :)

I tagged the windows upload properly, it should work if you uninstall the game and then install it again.
