### ISSUE TITLE
🏁 BROTHER WAKE UP ↔ v23.6.0

### ISSUE THREAD

**Issue by iqbal252** [itchio/itch-compatibility-watchlist#1356]
:rotating_light: game [BROTHER WAKE UP](https://tokan.itch.io/brother-wake-up) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/820a75cd753760cd6bb4bc6836aaf66f).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
The game only ships a 64-bit version, but you have a 32-bit version of windows.
