### ISSUE TITLE
🏁 Survival Game ↔ v23.6.0

### ISSUE THREAD

**Issue by jtrent238** [itchio/itch-compatibility-watchlist#1358]
:rotating_light: game [Survival Game](https://jtrent238.itch.io/survival-game) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3d74876c821d718b6df53243fda32696).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Did you remove the .exe file in-between launches? Or did an Antivirus do it for you? Did you see any security notices when launching the game?

**Comment by jtrent238** [comment]
no nothing

**Comment by jtrent238** [comment]
OK it did

![](https://puu.sh/yXjLn/6802d146aa.png)
