### ISSUE TITLE
🐧 Overland ↔ v23.6.0

### ISSUE THREAD

**Issue by rhmoller** [itchio/itch-compatibility-watchlist#1368]
:rotating_light: game [Overland](https://finji.itch.io/overland) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b61aaa322027d8ef7ca40bd7b0f035c6).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Well, if you SIGKILL the game, it quits :) Performing as expected here.

**Comment by rhmoller** [comment]
It happens every time I click the "Exit to Desktop" button in the game.
