### ISSUE TITLE
🏁 Cynthia Micro ↔ v23.6.0

### ISSUE THREAD

**Issue by GeorgeWL** [itchio/itch-compatibility-watchlist#1384]
:rotating_light: tool [Cynthia Micro](https://tesselode.itch.io/cynthia-micro) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3e76d26053588879f903bb0b3eb2a202).

:running: I tried running it cause wanted to try it out, but immediately recieved the error of "unabe to find executable" and then the app didn't run.

**Comment by fasterthanlime** [comment]
This is not meant to be a standalone application - it's just a DLL, probably something like a VST synth, that needs to be loaded into DAW. See https://www.thoughtco.com/what-are-vst-plug-ins-1817748 for more info.
