### ISSUE TITLE
🏁 Bonsai Worlds ↔ v23.6.0

### ISSUE THREAD

**Issue by smallg0at** [itchio/itch-compatibility-watchlist#1386]
:rotating_light: game [Bonsai Worlds](https://enricllagostera.itch.io/bonsai-worlds) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b82b9b98f21a0c63de48d30457855926).

:running: NO excutables found

**Comment by fasterthanlime** [comment]
The upload tagged as "windows" is in fact a `.air` file, which is an Adobe AIR application, but not packaged as a native executable.

The itch app needs a native executable to launch something.

I'd recommend getting in touch with the developer, asking them to upload a native windows build, not just the `.air` file.
