### ISSUE TITLE
🏁 Amorous ↔ v23.6.0

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#1389]
:rotating_light: game [Amorous](https://teamamorous.itch.io/amorous) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/725070ca8dcefbd2bd233d53765435b0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
![image](https://user-images.githubusercontent.com/7998310/35329387-f8ca028c-00ff-11e8-92f1-d842e8bfd7bc.png)

It looks like the game is badly packaged: the executable requires administrator privileges, even though no game should require it. The itch app will refuse to launch executables that require administrator privileges.

I'd recommend contacting the developer of the game and having them upload a build that doesn't require administrator privileges.
