### ISSUE TITLE
🏁 Barbershop Simulator ↔ v23.6.0

### ISSUE THREAD

**Issue by martin0909** [itchio/itch-compatibility-watchlist#1398]
:rotating_light: game [Barbershop Simulator](https://barbershopsimulator.itch.io/barbershop-simulator) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b860741fe5583f310a11d49c4495b9a3).

:running: Any additional details can go here!

**Comment by martin0909** [comment]
can des work

**Comment by martin0909** [comment]
kom now

**Comment by fasterthanlime** [comment]
1. Don't close/re-open issues many times, this doesn't make us react to your report faster
2. Looking at the log, it seems that the game wasn't properly installed (the folder is empty). Try uninstalling it and installing it again from the app.
