### ISSUE TITLE
🐧 Birdsketball ↔ v18.2.0

### ISSUE THREAD

**Issue by calexil** [itchio/itch-compatibility-watchlist#14]
:rotating_light: game [Birdsketball](https://waynetron.itch.io/birdsketball) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/04596220c6c4495b38404337fab66439).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Can you post the output of this command?

``` bash
file /home/jd/.config/itch/apps/Birdsketball/Birdsketball
```

**Comment by calexil** [comment]
file /home/jd/.config/itch/apps/Birdsketball/Birdsketball
/home/jd/.config/itch/apps/Birdsketball/Birdsketball: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=5743974ec12c6969665b9f31ad737cb1118df542, stripped

**Comment by fasterthanlime** [comment]
Does `-force-opengl` do anything there?
