### ISSUE TITLE
🏁 Stockboy ↔ v23.6.1

### ISSUE THREAD

**Issue by CassiePeele** [itchio/itch-compatibility-watchlist#1417]
:rotating_light: game [Stockboy](https://hamumu.itch.io/stockboy) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/456b5dbf54ce12c9b13595d29fb0c657).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
This game is using an unsupported installer type - I'd recommend reaching out to the developer, asking them for a [portable build](https://itch.io/docs/itch/integrating/platforms/windows.html) instead.
