### ISSUE TITLE
🐧 SCP Clicker ↔ v23.6.0

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#1418]
:rotating_light: game [SCP Clicker](https://guard13007.itch.io/scp-clicker) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c018d105a799913276fb0089cfdb5002).

:running: There is no executables

**Comment by fasterthanlime** [comment]
The linux version is a Love2D bundle, so the app won't be able to launch it for now.

You need to open a terminal, navigate to the directory where the game is installed (find that out with the "Show local files" button), and run "love thefile.love" - make sure you have love installed first :)
