### ISSUE TITLE
🏁 Trying ↔ v23.6.1

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#1422]
:rotating_light: game [Trying](https://yoloft.itch.io/trying) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c75652ba2d528d1f110bb34d1f62bbad).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
This is an unsupported installer type (stored in a .zip archive, to make things worse) based on the LHA archive format from 1998, apparently still popular in Japan and sometimes used by ID software?

I'd recommend reaching out to the developer and asking them to upload a [portable build](https://itch.io/docs/itch/integrating/platforms/windows.html) instead.
