### ISSUE TITLE
🐧 Knightin' ↔ v23.6.1

### ISSUE THREAD

**Issue by Xaaf** [itchio/itch-compatibility-watchlist#1425]
:rotating_light: Game [Knightin'](https://wolod.itch.io/knightin) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/77184535b41a4dce39f4893468ee75b9).

System: Linux (Deepin OS)
Error: Some required 32-bit libraries are missing: libnss3.so

Any fixes?

**Comment by fasterthanlime** [comment]
Yup, installing them!

```
sudo apt-get install libnss3:i386
```

I don't know how much support Deepin has for multiarch, or if it has different package names, but that's the general idea.

**Comment by Xaaf** [comment]
Okay, that error is now out of the way. I got another error though (they might keep coming for all missing packages?)
The `libgconf-2.so.4` library is now missing. I've tried `sudo apt-get install libgconf-2`, no results...
Again, you got a fix?

**Comment by fasterthanlime** [comment]
Use the `Search the contents of packages` form here to find the appropriate package: https://www.debian.org/distrib/packages

We're working on shipping a linux runtime to avoid that problem altogether in the near future :) /cc @GranPC

**Comment by Xaaf** [comment]
Okay, thanks!
