### ISSUE TITLE
🐧 Regular Human Basketball ↔ v23.6.1

### ISSUE THREAD

**Issue by tomtomme** [itchio/itch-compatibility-watchlist#1429]
:rotating_light: game [Regular Human Basketball](https://powerhoof.itch.io/regular-human-basketball) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a6d4f7171c69bd531fb31003b68c7222).

:running: Any additional details can go here!

**Comment by tomtomme** [comment]
game ran fine. this crash occured when hitting the quit button of the game. so no clean exit.

**Comment by fasterthanlime** [comment]
> game ran fine. this crash occured when hitting the quit button of the game. so no clean exit.

Alright, cool, that's just Unity games misbehaving on Linux again!
