### ISSUE TITLE
🏁 Aven Colony (Beta) ↔ v18.7.0

### ISSUE THREAD

**Issue by matthiasbuettner159** [itchio/itch-compatibility-watchlist#145]
:rotating_light: game [Aven Colony (Beta)](https://mothership.itch.io/aven-colony) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/0b58629d3d5e86e94789b5003532eaca).

:running: I installed the game via itch.io launcher and by downloading the zip file and it crashes at the same stage. I also installed the latest Version of Windows 10 as well as Java. I am running Windows on a MacBook Pro Early 2013, if this helps. I hope you can fix this issue soon and help me to play the game. Thanks a lot.

**Comment by fasterthanlime** [comment]
Hey, does running `Aven Colony Beta\Engine\Extras\Redist\en-us\UE4PrereqSetup_x64.exe` first help in any way?

**Comment by matthiasbuettner159** [comment]
Unfortunately this did not help. I've run the exe but it just told me to either uninstall or cancel. I clicked uninstall and then installed it again without success.

**Comment by fasterthanlime** [comment]
Ah :( Since this isn't an app bug, I'm going to close this thread, but you should check out the Bug Report section of the Aven Colony forums: http://avencolony.com/community/beta-bug-reports/ - they're good folks, I'm sure they'll be able to help you!
