### ISSUE TITLE
🐧 Fruits of a Feather ↔ v18.2.0

### ISSUE THREAD

**Issue by ibrokemypie** [itchio/itch-compatibility-watchlist#15]
:rotating_light: game [Fruits of a Feather](https://samuraipunk.itch.io/fruits-of-a-feather) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e2229c94001eca9031e472a847aac732).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like a 32-bit executable on 64-bit linux. I should add a test for that..

In the meantime, installing ia32-libs should probably let you run it!
