### ISSUE TITLE
🏁 BANG BANG BANG! ↔ v18.7.0

### ISSUE THREAD

**Issue by gkrnours** [itchio/itch-compatibility-watchlist#156]
:rotating_light: game [BANG BANG BANG!](https://sophieh.itch.io/bangbangbang) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/4dada8625a943b89665c92c8408bf7c4).

:running: Any additional details can go here!

```
[2016-09-13 @ 13:08:02.309]
[tasks/launch/native] out: API = LogonUser.
[tasks/launch/native] out: error code = 1330.
[tasks/launch/native] err: LogonUser
[tasks/launch/native] out: message    = The password for this account has expired.

```

I got the same error with MoonBase. I assume I need to change my sandbox sand. Pretty sure it's catlateral damage fault. These cats are wild.

Anyway, disabling the sandbox help.

**Comment by fasterthanlime** [comment]
Yep, looks like the default Win10 policy is to have expiring passwords, sandbox needs to be fixed. Thanks for the report!

**Comment by gkrnours** [comment]
I re-enabled the sandbox and the error came back. So I can test solution if needed

**Comment by fasterthanlime** [comment]
@gkrnours we'll release a new version of the app that knows to refresh the password — no fix needed on your side!

If you really want a workaround, you could remove the `itch-player` account (so that the app re-creates it), but that's a bit tricky since it doesn't show up in the user list (you have to do it from an Administrator shell).

**Comment by gkrnours** [comment]
nice :)
You can close then or I'll close after the new version is out if thing work as expected

**Comment by gkrnours** [comment]
Just to mention it still don't work with itch.io 1.8.9

**Comment by fasterthanlime** [comment]
Thanks for the report! 18.8.0 and 18.9.0 addressed some other problems, we'll release the sandbox fix today.

**Comment by fasterthanlime** [comment]
18.10.0 is out and ships with the windows sandbox fixes! It should ask you for your permission to perform initial sandbox setup, and then just work :)

**Comment by gkrnours** [comment]
The text in the dialog box is not ideal. It tell me about initial setup while it have already be done. But it's working as intended :)
:+1:
