### ISSUE TITLE
🏁 YIIK: Episode Prime “The MixTape Phantom and the Haunting of the Southern Cave.” ↔ v18.9.0

### ISSUE THREAD

**Issue by youngmadeof** [itchio/itch-compatibility-watchlist#164]
:rotating_light: game [YIIK: Episode Prime “The MixTape Phantom and the Haunting of the Southern Cave.”](https://ackkstudios.itch.io/yiik-episode-prime) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c91b700646a6fd2d5988d12e2d55d664).

:running: Any additional details can go here!

**Comment by youngmadeof** [comment]
Launches fine from the file location.

**Comment by fasterthanlime** [comment]
Looks like the dot at the end of the game's title was the issue. I'll release a new version that strips it when generating the install folder name, but you'll have to uninstall + install again (not re-install, that doesn't fix it) to have it working. Sorry for the trouble :(

**Comment by youngmadeof** [comment]
No problem. Thanks for dealing with so speedily.

**Comment by fasterthanlime** [comment]
18.10.0 is out, should be able to run fresh installs of YIIK,
