### ISSUE TITLE
🏁 Gat Life: Boyfriend Bar ↔ v18.10.0

### ISSUE THREAD

**Issue by ksirtet** [itchio/itch-compatibility-watchlist#170]
:rotating_light: game [Gat Life: Boyfriend Bar](https://emptyfortress.itch.io/gat-life-boyfriend-bar) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/8617a270343d23b7b433761e425a8526).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
One of the limitations of the sandbox on Windows right now is that you can't launch more than one game at a time — this error (CreateEnvironmentBlock failed) make me think you have another game (launched by itch) running in the background.

We'll address that in later releases, first by displaying a better error, then by lifting the limitation entirely (not trivial, but not impossible). Sorry for the disturbance in the meantime!

**Comment by ksirtet** [comment]
Thanks for your answer. I'm not trying to launch several games, my problem is for launching just one game. I can't lauch any game.

**Comment by fasterthanlime** [comment]
Can you try rebooting, starting itch again, and launching one game? It's entirely possible that a game is still running in the background but does not appear in the task bar.

**Comment by ksirtet** [comment]
I tried rebooting itch, I also downloaded and installed the new app today.

**Comment by fasterthanlime** [comment]
I was suggesting rebooting Windows, not itch :) the alternative is to look
in the Task Manager for a process being run as the "itch-player-*" user and
force it to quit, but that's a bit more complicated!

**Comment by ksirtet** [comment]
I just did it (reboot windows), and still have the error. I have a 32bit windows. I encountered this problem since a few weeks. I know how to use the task manager if needed.

**Comment by ksirtet** [comment]
It seems that now I only have the problem with ren'py games. The other games run properly.

**Comment by fasterthanlime** [comment]
Interesting! Could you post the log for a Ren'Py game that's failing to
launch?

**Comment by ksirtet** [comment]
Here is what Ren'py displays:
[renpy-rapport2.txt](https://github.com/itchio/itch-compatibility-watchlist/files/485288/renpy-rapport2.txt)

I have a similar "file not found" error for other Ren'py games:
[renpy-rapport3.txt](https://github.com/itchio/itch-compatibility-watchlist/files/485294/renpy-rapport3.txt)

Thank you for taking time to look at it!

**Comment by fasterthanlime** [comment]
Thanks for the logs, we'll be tracking that in https://github.com/itchio/isolate/issues/2 from now on!
