### ISSUE TITLE
🏁 RC-AirSim - RC Model Airplane Flight Simulator ↔ v18.5.0

### ISSUE THREAD

**Issue by JamieLivelink** [itchio/itch-compatibility-watchlist#171]
:rotating_light: game [RC-AirSim - RC Model Airplane Flight Simulator](https://fabricated-reality.itch.io/rc-airsim-rc-model-airplane-flight-simulator) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/fb599d8f0224d3e478ccd7ea34521f02).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Good news, we just released a fix for that particular problem! (/cc @GranPC).

Updating to version 18.10.0 of the app should fix your problem. You can use `Check for updates` from the user menu or download it right from https://itch.io/app (it'll keep your games installed).
