### ISSUE TITLE
🏁 Aven Colony (Beta) ↔ v18.10.0

### ISSUE THREAD

**Issue by SRombauts** [itchio/itch-compatibility-watchlist#173]
:rotating_light: game [Aven Colony (Beta)](https://mothership.itch.io/aven-colony) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5b184c1e105a09bf7bb23945dc631c62).

:running: It is broken since the last update of the itch.io app I did just a few minutes ago (it was about the sandbox)

Using directly AvenColony.exe in local files works like a charm.

Cheers!

**Comment by YoannMa** [comment]
Same for me : #174

**Comment by fasterthanlime** [comment]
Looks like a sandbox issue — I recommend working around it by disabling the sandbox before launching Aven Colony, we'll release a fix shortly. Sorry for the inconvenience!

**Comment by fasterthanlime** [comment]
My bad, this happens also when the sandbox isn't enabled, fixing now

**Comment by fasterthanlime** [comment]
v18.10.1 will be available in a few minutes and fixes this issue

**Comment by SRombauts** [comment]
Thanks, I will get the update tomorrow
