### ISSUE TITLE
🏁 Animal Inspector ↔ v18.10.0

### ISSUE THREAD

**Issue by wakefield-tech** [itchio/itch-compatibility-watchlist#175]
:rotating_light: game [Animal Inspector](https://tomastle.itch.io/animal-inspector) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/14408ea59a0041b38ac8ce06d235cec8).

:running: Any additional details can go here!

After the update from 9/20/16, some of my games won't launch, including Animal Inspector

**Comment by fasterthanlime** [comment]
Releasing v18.10.1 with a fix, should be available in a few minutes
