### ISSUE TITLE
🏁 Aven Colony (Beta) ↔ v18.10.0

### ISSUE THREAD

**Issue by clcanela** [itchio/itch-compatibility-watchlist#176]
:rotating_light: game [Aven Colony (Beta)](https://mothership.itch.io/aven-colony) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/23588eaa93aec266b4c353b90c521f9f).

:running: Game works ok when launched directly from it's exe file but it fails with itch's launcher

**Comment by fasterthanlime** [comment]
@clcanela v18.10.1 fixes that issues, sorry for the disturbance!
