### ISSUE TITLE
🐧 Ravenfield (Beta 3) ↔ v18.10.1

### ISSUE THREAD

**Issue by Teal1500** [itchio/itch-compatibility-watchlist#181]
:rotating_light: game [Ravenfield (Beta 3)](https://steelraven7.itch.io/ravenfield) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2dda1d14c8bdb57d45f696d72c9596b8).

:running: I launch the game and it gives me a SIGABRT error not sure why, my distro is debian testing

**Comment by fasterthanlime** [comment]
Hmm, it's a 32-bit game running on a 64-bit distro, maybe some libs are missing. What happens when you run `ldd` on the game's executable?

**Comment by Teal1500** [comment]
It appears to have been a Lib issue i installed libglu1-mesa:i386 and it fixed it, weird considering it didn't say anything in the terminal about it

**Comment by fasterthanlime** [comment]
> weird considering it didn't say anything in the terminal about it

Indeed, I think recent Unity versions load some libraries dynamically and just fail silently :(

**Comment by Teal1500** [comment]
> Indeed, I think recent Unity versions load some libraries dynamically and just fail silently :(

Nice thanks Unity
