### ISSUE TITLE
🐧 Gravitus Minus ↔ v18.10.1

### ISSUE THREAD

**Issue by shackra** [itchio/itch-compatibility-watchlist#194]
:rotating_light: game [Gravitus Minus](https://kometbomb.itch.io/gravitus-minus) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/75b8ef3ba0929a48d30e43bfb0a28be0).

:running: Any additional details can go here!

**Comment by kometbomb** [comment]
The log says that some of the libraries the game tried to load were for a x64 Linux, while yours is a i386 build.

This was my bad: for some reason some of the 32-bit libraries included in the download had been replaced with 64-bit libs. I have updated the download. Please download Gravitus Minus version 1.0.8, it should work on i386 platforms as well as on x86_64. Sorry for the inconvenience and thank you a lot for noticing this!

**Comment by fasterthanlime** [comment]
Closing this since it seems resolved, thanks for responding @kometbomb !

**Comment by shackra** [comment]
Thanks!

**Comment by shackra** [comment]
No problem, thanks! 

El 23 de octubre de 2016 11:37:03 GMT-06:00, Tero Lindeman notifications@github.com escribió:

> The log says that some of the libraries the game tried to load were for
> a x64 Linux, while yours is a i386 build.
> 
> This was my bad: for some reason some of the 32-bit libraries included
> in the download had been replaced with 64-bit libs. I have updated the
> download. Please download Gravitus Minus version 1.0.8, it should work
> on i386 platforms as well as on x86_64. Sorry for the inconvenience!
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/itchio/itch-compatibility-watchlist/issues/194#issuecomment-255602067

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
