### ISSUE TITLE
🐧 Offworld ↔ v18.10.1

### ISSUE THREAD

**Issue by JimmyBastos** [itchio/itch-compatibility-watchlist#199]
:rotating_light: game [Offworld](https://tengu-games.itch.io/offworld) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/153ce8292711549fa930d09318b3e981).

:running: Any additional details can go here!

OS: Arch Linux x86_x64
Processor type: Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
RAM: 3792 MB
Kernel Release: 4.7.6-1-ARCH

**Comment by garguelo46** [comment]
I cant run the game on Arch Linux x86_x64...
Processor type:  Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
RAM: 3792 MB
Kernel Release: 4.7.6-1-ARCH

**Comment by fasterthanlime** [comment]
Did you figure out what the problem was? (ENOENT indicates the file to be executed wasn't present on disk)

**Comment by garguelo46** [comment]
I know... But the game is on disk... I tried execute the binary and the bash returned a similar error... I tried another game and I've gotten the same error... Sorry, i think the problem is on Itch app...

**Comment by fasterthanlime** [comment]
Actually I think ENOENT can also be returned when trying to launch a 32-bit executable on 64-bit linux without multiarch!

**Comment by JimmyBastos** [comment]
Thanks bro!! Sorry about disturb...
