### ISSUE TITLE
🏁 GUN GODZ ↔ v18.10.1

### ISSUE THREAD

**Issue by BenjaminDruryStudent** [itchio/itch-compatibility-watchlist#201]
:rotating_light: game [GUN GODZ](https://vlambeer.itch.io/gun-godz) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/0409d5172983eeeb6d309c76ba5b1fdb).

:running: just tried to install the game using the itch app. It failed the first time, so I reinstalled the game, then failed again, hope this helps.

**Comment by fasterthanlime** [comment]
The GUN GODZ page says the game doesn't run properly on Windows 8 — I'd assume it doesn't run on Windows 10 either.
