### ISSUE TITLE
🐧 Serment - Contract with a Devil Alpha Demo ↔ v18.10.1

### ISSUE THREAD

**Issue by Glanzer** [itchio/itch-compatibility-watchlist#203]
:rotating_light: game [Serment - Contract with a Devil Alpha Demo](https://nkt-v2.itch.io/serment-contract-with-a-devil-alpha-demo) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/282b77abcf807529c7abacb1fd22ae86).

:running: Any additional details can go here!

The path
`/home/g/.config/itch/apps/Serment - Contract with a Devil Alpha Demo/-1.02-all/.sh`
looks wonky, the creator using $-signs instead of the letter 'S' might be part of the problem here.
The path should look like
`/home/g/.config/itch/apps/Serment - Contract with a Devil Alpha Demo/$ermentDemo-1.02-all/$ermentDemo.sh`
Directly running
`$ermentDemo.sh`
from the game's local files works fine - it's most likely an issue with correctly escaping paths. (on Linux, could probably be an issue for OSX too)

**Comment by fasterthanlime** [comment]
Closing in favor of https://github.com/itchio/itch/issues/940 (will be using this issue for reference!)
