### ISSUE TITLE
🏁 SporeWar ↔ v18.10.1

### ISSUE THREAD

**Issue by jacobpeltola** [itchio/itch-compatibility-watchlist#208]
:rotating_light: game [SporeWar](https://boxmountaingames.itch.io/sporewar) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/37679f921a765f1b5b1d46e2ee45f59e).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Solved this, see https://github.com/itchio/itch/issues/943 for resolution.
