### ISSUE TITLE
🏁 Reap What You Sow ↔ v18.10.1

### ISSUE THREAD

**Issue by Trent-0** [itchio/itch-compatibility-watchlist#209]
:rotating_light: game [Reap What You Sow](https://kyatt.itch.io/reap-what-you-sow) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e41b6de995c59c0f0dd11936762ca7e5).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Same question as #210 — it looks like installation may have been interrupted somehow. Got enough disk space? Anything else funny happen during install?

**Comment by fasterthanlime** [comment]
Solved this, see https://github.com/itchio/itch/issues/943 for resolution.
