### ISSUE TITLE
🐧 Birth of the Empires ↔ v18.3.0

### ISSUE THREAD

**Issue by sarkanyi** [itchio/itch-compatibility-watchlist#21]
:rotating_light: game [Birth of the Empires](https://blotunga.itch.io/birth-of-the-empires) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7dcd2b4f0cd747e5dbc67978a5b2396b).

:running: Just install and run under Linux.

**Comment by fasterthanlime** [comment]
Interesting, looks like the game ships its own JVM, but the app tries to launch with system java anyway. If you don't have java installed on your system, that's probably why it fails.

**Comment by sarkanyi** [comment]
I have java but some people don't. Also it should somehow run the "bote" binary which launches the integrated jvm.

**Comment by sarkanyi** [comment]
I have the same problem on Windows, the itch app tries to start the jar directly instead of running the "bote.exe" which launches the game using the built-in jvm.

**Comment by sarkanyi** [comment]
It would be nice to have a way to supply a default command (or list of default commands). Also for example it would be nice if we could provide command line options too for some of the commands. For example in my case running the game with "--editor" runs the game in editor mode, which can be used for modders.

**Comment by fasterthanlime** [comment]
> Also it should somehow run the "bote" binary which launches the integrated jvm.

I agree, opened https://github.com/itchio/itch/issues/819 to track that.

> It would be nice to have a way to supply a default command (or list of default commands). Also for example it would be nice if we could provide command line options too for some of the commands. For example in my case running the game with "--editor" runs the game in editor mode, which can be used for modders.

The game's developer can expose that with a [manifest](https://itch.io/docs/itch/integrating/manifest.html) — as for letting app users do that, see https://github.com/itchio/itch/issues/366

**Comment by sarkanyi** [comment]
Ok, thanks, I will try it with manifests and get back to you.

**Comment by sarkanyi** [comment]
Nvm, I was packaging the game the wrong way. It included the directory...

**Comment by sarkanyi** [comment]
Ok, found the reason for the 255 error value, it was because of libgdx. Still I don't understand how to use multiple actions in the manifest. If I set for example
[actions.play]
...
[action.editor]
Then the actions play isn't executed.
The only way I managed to get the game running the binary was using
[[actions]]
name = "play"
path = "bote"

**Comment by fasterthanlime** [comment]
@sarkanyi Ah, I see the 'localization' section of the docs is misleading. You can achieve multiple actions simply by having multiple `[[actions]]` blocks, like so:

``` toml
[[actions]]
name = "play"
path = "bote"

[[actions]]
name = "editor"
path = "bote"
args = ["--editor"]
```

Note: I don't think the app actually relays `args` yet, cf. https://github.com/itchio/itch/issues/820

**Comment by sarkanyi** [comment]
Yupp, args are not yet relayed, but I can create my manifest like this for now.
Thanks!
