### ISSUE TITLE
🏁 DMCA's Sky ↔ v18.10.1

### ISSUE THREAD

**Issue by Trent-0** [itchio/itch-compatibility-watchlist#210]
:rotating_light: game [DMCA's Sky](https://asmb.itch.io/dmcas-sky) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/354b71e344fd294eff4352a6cabcf412).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Is there an .exe in the installed folder?

**Comment by fasterthanlime** [comment]
Solved this, see https://github.com/itchio/itch/issues/943 for resolution.
