### ISSUE TITLE
🏁 Don't Settle For Less ↔ v18.10.1

### ISSUE THREAD

**Issue by Faedelity** [itchio/itch-compatibility-watchlist#213]
:rotating_light: game [Don't Settle For Less](https://velvetlobster.itch.io/dont-settle-for-less) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c7849ea411d4613e3a181d24a7aaef60).

:running: The Data folder is missing from both this and the manual download for Windows.

**Comment by fasterthanlime** [comment]
I suggest leaving a comment directly on the game page, since that's not an app issue!

**Comment by Faedelity** [comment]
Okay, done. Thanks for redirect. :-)
