### ISSUE TITLE
🐧 Pixel Dungeon ↔ v18.10.1

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch-compatibility-watchlist#215]
:rotating_light: game [Pixel Dungeon](https://watabou.itch.io/pixel-dungeon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d484cfc6cce36098ad143bcc28e7505c).

:running: A java game, I assume since I don't have java installed manually that's the reason it won't launch. Maybe do a check for java games and notify if they don't have it installed? Would be even better for devs to bundle it though.

**Comment by fasterthanlime** [comment]
Sounds like a plan! Closing in favor of https://github.com/itchio/itch/issues/945
