### ISSUE TITLE
🍎 Diaries of a Spaceport Janitor ↔ v19.0.0

### ISSUE THREAD

**Issue by CiaraBurkett** [itchio/itch-compatibility-watchlist#233]
:rotating_light: game [Diaries of a Spaceport Janitor](https://tinybuild.itch.io/diaries-of-a-spaceport-janitor) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/efa1c1d5d6f38e0556ef8b60d53599d0).

**Comment by fasterthanlime** [comment]
Interesting, it looks like when the app updated, it created another app bundle (folder that ends in `.app`) but didn't remove the other one. The app still tries to launch the first one, so it doesn't work out well.

If you use `Show local files` and move `DiariesOfASpaceportJanitor_mac.app` to trash, it should start working again :) I'll think about preventing this particular case.

**Comment by CiaraBurkett** [comment]
Yup, that did the trick! Thanks so much Amos!
