### ISSUE TITLE
🏁 Character Randomizer ↔ v19.0.0

### ISSUE THREAD

**Issue by Kromzem** [itchio/itch-compatibility-watchlist#237]
:rotating_light: game [Character Randomizer](https://100mph-games.itch.io/character-randomizer) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a9efb476e9461d96bb135f29e1bbd719).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
This error happens when another game is still running in the sandbox. It's a current limitation of the itch.io sandbox on Windows, we're working on a fix.

In the meantime, close any processes running as `itch-player-XXXX` from the process explorer, and it should start working again.
