### ISSUE TITLE
🏁 Right Click to Necromance ↔ v19.0.0

### ISSUE THREAD

**Issue by Knuds1** [itchio/itch-compatibility-watchlist#238]
:rotating_light: game [Right Click to Necromance](https://juicybeast.itch.io/right-click-to-necromance) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9acfcde8e01fbeb2a9361e8a0be61d67).

:running: Any additional details can go here!

No executable found in Windows bundle.

**Comment by fasterthanlime** [comment]
Hmm looks like https://github.com/itchio/butler/issues/83 is back — looking into it

**Comment by fasterthanlime** [comment]
I released [butler 1.3.0](https://github.com/itchio/butler/issues/87) which fixes it. All you need to do is quit the itch app (using Ctrl+Q, or right click on the tray icon and pick 'Quit', or choose 'Quit' from the user menu on the bottom left), start it again, then reinstall the game, and it should work fine.
