### ISSUE TITLE
🏁 Right Click to Necromance ↔ v19.0.0

### ISSUE THREAD

**Issue by zeusrs** [itchio/itch-compatibility-watchlist#240]
:rotating_light: game [Right Click to Necromance](https://juicybeast.itch.io/right-click-to-necromance) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7348b64a4259e7b274b486c002c896f8).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
See #238 — it was a bug, I fixed it, quitting the itch app completely and starting it again, then reinstalling RCTN should do the trick!
