### ISSUE TITLE
🏁 Troll ↔ v18.10.1

### ISSUE THREAD

**Issue by Caloxeno** [itchio/itch-compatibility-watchlist#241]
:rotating_light: game [Troll](https://rednax.itch.io/troll) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6de0046d4bf745c13c7b2a2d8a62b78b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
I think this is the same issue as https://github.com/itchio/itch-compatibility-watchlist/issues/238 — see that link for instructions, I've fixed the bug since!
