### ISSUE TITLE
🏁 Insatia ↔ v19.0.0

### ISSUE THREAD

**Issue by gggamers** [itchio/itch-compatibility-watchlist#243]
:rotating_light: game [Insatia](https://kozinaka.itch.io/insatia) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f3bd5054cddc9ea434c9b5fb962e0c15).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like the game just crashed :( same would happen when launched without the app! Maybe contact the developer saying the exe quit with code "3221225781" ?

Before that, you may want to try the instructions here: https://github.com/itchio/itch-compatibility-watchlist/issues/238#issuecomment-258675353 — you may have been hit by an unzip bug.
