### ISSUE TITLE
🐧 Space Jammers ↔ v18.10.1

### ISSUE THREAD

**Issue by StripedMonkey** [itchio/itch-compatibility-watchlist#244]
:rotating_light: game [Space Jammers](https://spreadshot.itch.io/space-jammers) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e3f1bbad5d7326121e7353017fb68d96).

:running: Any additional details can go here!
First try, I'm runing Arch Linux. If I look at the "version" it says (DEMO Mac v0.400 (app.zip)) which tells me that this isn't really packaged for Linux.

**Comment by fasterthanlime** [comment]
Haha, it looks like the platform tags were switched around :) I'll fix it.

**Comment by fasterthanlime** [comment]
I fixed the tags, try uninstalling/installing Space Jammers again and you should have the Linux build!
