### ISSUE TITLE
🐧 Overland ↔ v19.0.0

### ISSUE THREAD

**Issue by corq** [itchio/itch-compatibility-watchlist#247]
:rotating_light: game [Overland](https://finji.itch.io/overland) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/0ef67b5152d478d8b344b6c60bb9c1c4).

:running:  occured while attempting to exit game

**Comment by fasterthanlime** [comment]
Yep! Sometimes Overland exits with a non-zero code. Still not sure why — doesn't really affect gameplay though.

**Comment by corq** [comment]
Agreed, the crash just prompted me to send so I have. I've had no trouble
at all during the game, but that msg seems to often happen when trying to
exit.

Thanks for all your work!
