### ISSUE TITLE
🏁 LUZ ↔ v19.0.0

### ISSUE THREAD

**Issue by Alloyed** [itchio/itch-compatibility-watchlist#250]
:rotating_light: game [LUZ](https://snekdev.itch.io/luz) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/4cc831f1a8075b591a21a4e4945a40cb).

:running: passes up an undefined prop error on start, seems like a bug

**Comment by fasterthanlime** [comment]
See #238 — I suspect either the app is using a buggy extractor (if it's been running for a while) or the install somehow didn't finish properly. A clean install on v19.0.0 worked for me!

Try:
- Quitting the app (Ctrl+Q), starting it up again — see if it briefly displays "Installing dependency butler v1.4.0"
- Then, uninstalling the game (fully) and installing it again

**Comment by Alloyed** [comment]
reinstalling worked <3
