### ISSUE TITLE
🏁 Shotgun Farmers - Alpha Prototype ↔ v19.0.0

### ISSUE THREAD

**Issue by SeanFrolander** [itchio/itch-compatibility-watchlist#263]
:rotating_light: game [Shotgun Farmers - Alpha Prototype](https://qazitv.itch.io/shotgun-farmers-alpha) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/19a3a837c2f61645c5d0d0bd737e89e2).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Since you just closed this, I'm assuming it's working with itch v23.4.1 ?

Looking at the logs, it looks like a sandbox bug we fixed a long time ago.
