### ISSUE TITLE
🏁 Niagara ↔ v18.6.2

### ISSUE THREAD

**Issue by TruenoSolitario** [itchio/itch-compatibility-watchlist#264]
:rotating_light: game [Niagara](https://pandastudios.itch.io/niagara) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/255c13e7387244eded67d1b6f59c2612).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
interesting, `spawn UNKNOWN` usually happens when launching an installer that requires admin privileges without admin privileges, but in that case... it should be the main executable of the game? I'm not sure what's going on.

**Comment by TruenoSolitario** [comment]
Does it work on windows 32bits?
Thanks!

**Comment by fasterthanlime** [comment]
Oh, that explains it! It's a 64-bit executable.

Case solved! If you'd like 32-bit support, get in touch with the developers of the game in the comment section.
