### ISSUE TITLE
🐧 SEUM: Speedrunners from Hell Demo ↔ v18.3.0

### ISSUE THREAD

**Issue by rauldipeas** [itchio/itch-compatibility-watchlist#28]
:rotating_light: game [SEUM: Speedrunners from Hell Demo](https://pinestudio.itch.io/seum-demo) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/475baa847a4abc62fb757dee1e2c46ed).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
cf. #29, same symptoms
