### ISSUE TITLE
🏁 Breach & Clean ↔ v19.0.0

### ISSUE THREAD

**Issue by Frabs69** [itchio/itch-compatibility-watchlist#288]
:rotating_light: game [Breach & Clean](https://ramiismail.itch.io/breach-and-clean) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c3ba9f146222f732030e2ee72f2ef87b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Duplicate of #287
