### ISSUE TITLE
🏁 Winds of Revenge ↔ v19.0.0

### ISSUE THREAD

**Issue by Frxn69** [itchio/itch-compatibility-watchlist#296]
:rotating_light: game [Winds of Revenge](https://allshar.itch.io/winds-of-revenge) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9143a824135923b9d71b4ca824045b1a).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Duplicate of #295
