### ISSUE TITLE
🏁 Seven Sages ↔ v18.0.0

### ISSUE THREAD

**Issue by Nevon** [itchio/itch-compatibility-watchlist#3]
:rotating_light: game [Seven Sages](https://ghostfromthevoid.itch.io/sevensages) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c7c754f6b1ff4962945d8df25830bcd0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Do you have Java installed? itch tries to launch it, but has no logic for checking whether it's installed or not beforehand.

**Comment by Nevon** [comment]
I do, yes. If I manually run the game, it works fine.

**Comment by fasterthanlime** [comment]
(Note that Seven Sages runs fine for me (with sandbox disabled - see https://github.com/itchio/itch/issues/744 for a separate issue))

**Comment by Nevon** [comment]
Yup, I have Java installed, and it's in my path. What I suspect may have happened, however, is that I launched Itch before installing Java (though it was installed when I tried to launch the game).

I am able to launch the game from the Itch client now, so I can only assume that's what happened.

**Comment by fasterthanlime** [comment]
> What I suspect may have happened, however, is that I launched Itch before installing Java

That's definitely it - it wasn't in the PATH when itch was launched, so it couldn't find it :) case closed!
