### ISSUE TITLE
🐧 GunSpinning VR ↔ v18.4.0

### ISSUE THREAD

**Issue by lahtis** [itchio/itch-compatibility-watchlist#32]
:rotating_light: game [GunSpinning VR](https://demonixis.itch.io/gunspinning-vr) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9fbdb9d09fff923663cdf18b53b683cb).

:running: Any additional details can go here
Exit the game and game crashing exit screen. Only background show my desktop.

**Comment by fasterthanlime** [comment]
Hey, I see you posted directly to the game's forums. That's good! It doesn't look like it's an app-related issue, so I'll be closing this (but feel free to point the developer to it since it contain info that may be useful to them).

**Comment by lahtis** [comment]
fixed.

**Comment by fasterthanlime** [comment]
Awesome, thanks for reporting back!
