### ISSUE TITLE
🐧 Ramblings ↔ v20.0.2

### ISSUE THREAD

**Issue by codyatwork** [itchio/itch-compatibility-watchlist#381]
:rotating_light: game [Ramblings](https://boaheck.itch.io/ramblings) is broken for me.

  :book: Here's the complete [debug log](https://gist.github.com/55467f251af55d0008e412d3fd2a26cd).

  :running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Manifest is invalid, I left a comment on the game page with hints for the author
