### ISSUE TITLE
NeuroIDE

### ISSUE THREAD

**Issue by 0x0961h** [itchio/itch-compatibility-watchlist#4]
> App Version: **v18.0.0**
> Sandbox: **disabled**

[**NeuroIDE**](https://0x0961h.itch.io/neuroide) is a HTML5-only game. It was made with Java/LibGDX and then exported to HTML5. 

When I click **Launch** in app I get a blank window:

![image](https://cloud.githubusercontent.com/assets/5813735/16542523/77589994-40ac-11e6-82ff-7a1e88670b62.png)

It works on the itch.io, though.

**Comment by fasterthanlime** [comment]
You can open the chrome devtools with Shift+F12. Doesn't look like any network requests are being denied, nor do I see script errors, but the DOM does appear empty. No idea so far!

**Comment by fasterthanlime** [comment]
Does the game rely on some particular event being emitted to start up? It doesn't look like it's doing much of anything at this point, and since the scripts are (seemingly) obfuscated, it's hard to tell!

**Comment by 0x0961h** [comment]
Yeah, I see. Well, basically, the game is launched via **CyberPunkJam();** line in **CyberPunkJam/CyberPunkJam.nocache.js** file. It starts the complex GWT magic and -- voila! -- game launches.

**Comment by 0x0961h** [comment]
**CyberPunkJam/CyberPunkJam.nocache.js** is included in **\<script\>** tag within the **index.html** file:

```

<!DOCTYPE html>
<html>
<head>
    <title>NeuroIDE</title>
</head>
<body bgcolor="black">
<div style="margin-bottom: 16px"><span style="font-size: 12px; font-family: Arial, Tahoma, Verdana; color: #fff"><strong>NeuroIDE</strong>, made by <a href="https://twitter.com/0x0961h" style="color: #66b; text-decoration: none;">@0x0961h</a> for <strong>Cyberpunk Jam</strong></span></div>
<script src="CyberPunkJam/CyberPunkJam.nocache.js"></script>
</body>
</html>
```

**Comment by fasterthanlime** [comment]
@0x0961h how about only calling CyberPunkJam() when the dom is ready? something like:

```javascript
document.addEventListener('DOMContentLoaded', CyberPunkJam)
```

Does running `CyberPunkJam()` manually in the chrome console do anything currently?

**Comment by 0x0961h** [comment]
It gives me `VM408:1 Uncaught ReferenceError: CyberPunkJam is not defined(…)`. I can't even find this function in the source code of the app page.

**Comment by 0x0961h** [comment]
Okay, so, I did the `window.location.replace('C:/Users/0x0961h/AppData/Roaming/itch/apps/NeuroIDE/index.html');` and bam!

![image](https://cloud.githubusercontent.com/assets/5813735/16544397/6506a580-4104-11e6-83ba-f7854205dd19.png)

**Comment by fasterthanlime** [comment]
> Okay, so, I did the window.location.replace('C:/Users/0x0961h/AppData/Roaming/itch/apps/NeuroIDE/index.html'); and bam!

HTML games are served from a temporary http servers for a few reasons, so loading directly from filesystem isn't really a good fix :) I'll look into it more.

**Comment by 0x0961h** [comment]
Oh, I know it's not, I'm just saying about how I was able to run it. :)

**Comment by fasterthanlime** [comment]
Alright, looks like the app is opening the wrong .html file:

```
[2016-07-04 @ 13:50:18.734] [tasks/launch] looking for manifest @ "D:\Games\Itch\apps\NeuroIDE\.itch.toml"
[2016-07-04 @ 13:50:18.745] [tasks/launch] entry point: D:\Games\Itch\apps\NeuroIDE\CyberPunkJam\092AF3FB9C403154342E2909AA40667D.cache.html
[2016-07-04 @ 13:50:18.745] [tasks/launch] starting at resolution 1040x635
[2016-07-04 @ 13:50:18.781] [tasks/launch] serving game on port 52926
[2016-07-04 @ 13:53:14.164] [tasks/launch] shutting down http server on port 52926
```

**Comment by fasterthanlime** [comment]
Found the bug, fixed it, shipping new version!

![neuroide](https://cloud.githubusercontent.com/assets/7998310/16559944/a290e5f4-41f0-11e6-92a6-a528e88ead22.png)

**Comment by 0x0961h** [comment]
Oh, nice! Thank you!

**Comment by fasterthanlime** [comment]
18.3.0 shipped with the fix, works great for me!
