### ISSUE TITLE
🏁 Kenney Game Assets 2 ↔ v18.4.0

### ISSUE THREAD

**Issue by kostasEf** [itchio/itch-compatibility-watchlist#43]
:rotating_light: assets [Kenney Game Assets 2](https://kenney.itch.io/kenney-game-assets-2) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e14a5f14e09ba77b4fdb0035d713762b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
@kostasEf do you remember if you clicked 'Install' from the game' page, or from a collection / the 'library' tab?

**Comment by kostasEf** [comment]
This was already installed and I could open it just fine. Then I noticed
there was an update for itch and after updating I had this error (I had not
updated for 3 months). Uninstalling and installing again solved this issue.

**Comment by fasterthanlime** [comment]
Alright cool, that issue shouldn't appear again, please re-open if it does!
