### ISSUE TITLE
🏁 Blackscreen Simulator BETA ↔ v18.4.0

### ISSUE THREAD

**Issue by Myselfminer** [itchio/itch-compatibility-watchlist#45]
:rotating_light: game [Blackscreen Simulator BETA](https://mysi.itch.io/blackscreen-simulator) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b5fa723de344a7f3f6882307580bfc34).

:running: The Problem is that itch launches the StartGame.exe, which is not made for direct launches. Maybe an option to add a "start command" to the game would fix such problems, bacause the game needs to be started with "python launcherAlternate.py"

**Comment by fasterthanlime** [comment]
That sounds like a problem the developer should fix themselves. There's no plan for the app to support installing python just to run games (it's not that common, compared to, say, Love2D, or Adobe AIR games).

Feel free to point them to http://www.py2exe.org/ ! 🌟

**Comment by Myselfminer** [comment]
There are plenty of python files wich are started or imported, but py2exe just compiles one script, not it's imports (by the way, py2exe is deprecated). I tried to compile some files, but thats the problem with the  StartGame.exe. The Compiled file does tings it didn't do in the source file.

**Comment by Myselfminer** [comment]
You could youself to run the StartGame.exe: The game will behave weird (crash reports, Splahes). Start the launcherAlternate.py: Everything's fine. And the StartGame.exe is the compiled launcherAlternate.py

**Comment by fasterthanlime** [comment]
> by the way, py2exe is deprecated

Maybe http://cx-freeze.sourceforge.net/ then? The problem is not "compiling", it's distributing everything the game needs to be ran — expecting players to install python just to play the game is increasing friction by a lot.
