### ISSUE TITLE
🏁 Calling Cipher ↔ v22.2.0

### ISSUE THREAD

**Issue by LilithDeLil** [itchio/itch-compatibility-watchlist#473]
:rotating_light: game [Calling Cipher](https://impqueen.itch.io/calling-cipher) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e8fcc9582c5de75f42f37e0b85e200b1).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Did you manage to solve it? It looks like the app wasn't able to find an .exe file in the game's install folder.
