### ISSUE TITLE
🐧 Dungeon Escape (demo) ↔ v18.4.0 - It doesn't launch

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#48]
:rotating_light: game [Dungeon Escape (demo)](https://lehha95.itch.io/dungeon-escape) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/15fb2ecdddc7591354bfeb4fc9aab09a).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
It looks like the developer only ships a 32-bit build of the game, and doesn't include libXcursor.

Installing libxcursor1:i386 should let you run it, although the developer should take a look at https://itch.io/docs/itch/integrating/platforms/linux.html

**Comment by ghost** [comment]
OK, thanks for your quick reply. I will try to do that.

**Comment by ghost** [comment]
Just to let you know, I installed libxcursor1:i386 (using the command 'apt
install libxcursor1:i386' at the terminal, I'm not sure if that's the
correct way) but it didn't happen anything. Still I'm getting the same
error.

**Comment by fasterthanlime** [comment]
> Still I'm getting the same error.

Other libraries are probably missing. You can find out by using 'Examine the cause of the problem', and looking for lines like that in the log:

```
[2016-08-02 @ 04:59:01.187] [tasks/launch/native] err: /home/user/.config/itch/apps/Dungeon Escape demo/Linux 0.7.3/Dungeon Escape.x86: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory
```

Then googling `ubuntu package libXcursor.so.1` (or whatever the missing library is), then installing the i386 variant of it

**Comment by ghost** [comment]
I installed the following libraries: 'libxcursor', 'libxrandr' and 'ia32-lib'. Now a menu appears where I can choose the resolutions and the level of detail ('Maximum' is the only choice). After that, the game suddenly crashes, and the following message appears: 'Its last words were: killed by signal SIGABRT'.

:book: Here's the complete [debug log](https://gist.github.com/66cb156cb31b054cad26c272404cd403).

The developer was already informed about this whole report.
