### ISSUE TITLE
🐧 Ravenfield (Beta 2) ↔ v18.4.0 - It doesn't launch

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#49]
:rotating_light: game [Ravenfield (Beta 2)](https://steelraven7.itch.io/ravenfield) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7c9ed1864f222ff77b4a40d9e771d373).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Exact same cause as #49

**Comment by ghost** [comment]
I installed the following libraries: 'libxcursor', 'libxrandr' and 'ia32-lib'. Now the game works excellent, thanks. Though, at the beginning, if I try to select "Beautiful" or "Fantastic" level of detail, the game crashes with the same message as #48 ('killed by signal SIGABRT').

I will try to contact the developer about these issues.
