### ISSUE TITLE
🏁 Raft ↔ v22.2.0

### ISSUE THREAD

**Issue by mondmond1212** [itchio/itch-compatibility-watchlist#494]
:rotating_light: game [Raft](https://raft.itch.io/raft) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b1ead45f1129f1c3d47bee1b48ad68a2).

:running: Any additional details can go here!

**Comment by mondmond1212** [comment]
mondmond1212_1155

**Comment by mondmond1212** [comment]
Hi mond

**Comment by mondmond1212** [comment]
Hi

**Comment by mondmond1212** [comment]
Hi

**Comment by fasterthanlime** [comment]
This is a 64-bit game, it won't run on 32-bit Windows. Uninstall it and install it again - this time, choosing the "Win32" version, not the "Win64" one.

By the way, spamming an issue is a good way to get banned :) Please don't.
