### ISSUE TITLE
🏁 The Endless Express ↔ v18.0.0

### ISSUE THREAD

**Issue by eliseiscool1706** [itchio/itch-compatibility-watchlist#5]
:rotating_light: game [The Endless Express](https://vltmn.itch.io/the-endless-express) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2b25f6b4be2c54580fbc0b2b1d6da8ab).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Hard to say what happened here. Did any window pop up? Are you able to launch the game directly if you 'Show local files' and double-click on `The Endless Express x64.exe` manually?

**Comment by eliseiscool1706** [comment]
I opened it using the itch.io desktop app and it wouldn't open. It just said report broken...

**Comment by fasterthanlime** [comment]
I'm wondering if maybe your windows installation is 32-bit? You can find out by launching a command-line window (Windows-R, type 'cmd.exe', hit enter) and typing the following:

```
wmic OS get OSArchitecture
```

then pressing enter.

It should print something likeL

```
OSArchitecture
64-bit
```

(or 32-bit).

**Comment by eliseiscool1706** [comment]
Yeah it's 32 bit 

Date: Tue, 26 Jul 2016 15:04:00 -0700

**Comment by fasterthanlime** [comment]
@eliseiscool1706 newer versions of the app (you can grab the latest from https://itch.io/app) let you pick which download you want to use, so just uninstall, click install again, pick `Windows x86` and you should be fine :)
