### ISSUE TITLE
🏁 Tonari no Totoro - Fan Game ↔ v23.0.0

### ISSUE THREAD

**Issue by Eliepse** [itchio/itch-compatibility-watchlist#559]
:rotating_light: game [Tonari no Totoro - Fan Game](https://johan-aronson.itch.io/tonari-no-totoro-fan-game) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/49443aff5b83eab25251e319c0a170c1).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like an unsupported type of installer
