### ISSUE TITLE
🐧 Raft ↔ v23.0.0

### ISSUE THREAD

**Issue by blargle-ragequit** [itchio/itch-compatibility-watchlist#562]
:rotating_light: game [Raft](https://raft.itch.io/raft) crashes on exit for me.

:book: Here's the complete [debug log](https://gist.github.com/fd70f2749268b58c91ed8cd2671fc773).

:running: I was playing the linux version, started playing a new save, then exited to main menu and quit, and then the game crashed and prompted an error report.

**Comment by fasterthanlime** [comment]
Since it doesn't seem to be an app bug, it's probably best to post this thread (because it contains logs) directly to the game's [comments section](https://raft.itch.io/raft/community)
