### ISSUE TITLE
🏁 Manifold Garden ↔ v18.4.0

### ISSUE THREAD

**Issue by danewheaton** [itchio/itch-compatibility-watchlist#59]
:rotating_light: game [Manifold Garden](https://williamchyr.itch.io/manifoldgarden) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f36476d507a6acf54d52837fc7136439).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Duplicate of #58 - fixed by [18.6.0](https://github.com/itchio/itch/releases/tag/v18.6.0) which was just released.
