### ISSUE TITLE
NECLiD and Project MONSTER

### ISSUE THREAD

**Issue by 0x0961h** [itchio/itch-compatibility-watchlist#6]
> App Version: **v18.0.0**
> Sandbox: **enabled/disabled**

[**NECLiD**](https://0x0961h.itch.io/neclid) and [**Project MONSTER**](https://0x0961h.itch.io/project-monster) are both Java games made with LibGDX.

# **Part 1.** Sandbox disabled

~~Game launches, everything is good. But when I close the window I get the error:~~

![image](https://cloud.githubusercontent.com/assets/5813735/16542555/7e546fe2-40ad-11e6-81b8-1ad87da1ff86.png)

~~Which is weird, because it's an okay. Actually, the number makes me think about it being a **long** variable, which means it turns exit code -1 from app into error. Code -1 is thrown because of this param:~~

```
/** whether to call System.exit() on tear-down. Needed for Webstarts on some versions of Mac OS X it seems **/
public boolean forceExit = true;
```

~~When I set it to false I get the 0 exit code.~~

Okay, I got it, it's for the Web Start Java apps on Mac OS and I don't use it. The case closed.

# **Part 2.** Sandbox enabled

I got this: 

![image](https://cloud.githubusercontent.com/assets/5813735/16542648/1cd5b9b6-40b1-11e6-9842-faa2f47e7a1e.png)

I thought it was a problem with access rights (since itch.io app asked me to click OK on UAC alert and my UAC is off), but **Ultra Hat Dimension**, **Magbot** and **Reap** launched successfully. Another Java game I have, **Seas of Scred**, doesn't want to start either, but it doesn't even give me an exception or anything.

When I turn off Sandbox, all the games, that experienced problems before, launch flawlessly.

**Comment by fasterthanlime** [comment]
> Another Java game I have, Seas of Scred, doesn't want to start either, but it doesn't even give me an exception or anything.

This is most likely due to https://github.com/itchio/itch/issues/744

**Comment by 0x0961h** [comment]
Yeah, debug log mentions **CreateProcessWithLogonW**. I think we can close this issue then.
