### ISSUE TITLE
🏁 Breach & Clean ↔ v18.5.0

### ISSUE THREAD

**Issue by senaayazberat** [itchio/itch-compatibility-watchlist#62]
:rotating_light: game [Breach & Clean](https://ramiismail.itch.io/breach-and-clean) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6fe72ad891bafffd7c207c617dae27b9).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Duplicate of #61
