### ISSUE TITLE
🏁 Sacramento ↔ v18.5.0

### ISSUE THREAD

**Issue by TheZeldaZone** [itchio/itch-compatibility-watchlist#63]
:rotating_light: game [Sacramento](https://dziff.itch.io/sacramento) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/03602d9d7c819a16822de3ce56e1ac92).

:running: Actually nothing launches from Itchio in my client anymore. I have to open the folder directly (the games all work fine). Reinstalled, no worky

**Comment by fasterthanlime** [comment]
18.6.0 is out, fixes that problem.
