### ISSUE TITLE
🏁 Aven Colony (Beta) ↔ v23.1.0

### ISSUE THREAD

**Issue by Danidane** [itchio/itch-compatibility-watchlist#639]
:rotating_light: game [Aven Colony (Beta)](https://mothership.itch.io/aven-colony) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e60a80db061d4f50778ffc140fa91878).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
duplicate of #638
