### ISSUE TITLE
🏁 Tone Friends ↔ v23.2.0

### ISSUE THREAD

**Issue by qb20nh** [itchio/itch-compatibility-watchlist#643]
:rotating_light: game [Tone Friends](https://01010111.itch.io/tone-friends) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b81ab7d49b4e3981055958bc209b7302).

:running: I'm using itch sandbox, and I have a separate admin account.

**Comment by qb20nh** [comment]
Adobe AIR is very confused about using a separate account for privilege elevation.

**Comment by fasterthanlime** [comment]
From the logs, it looks like the sandbox isn't set up correctly.

```
[2017-02-02 @ 06:47:22.738] [sandbox-common] tending to need {"type":"user","err":"","code":1}
[2017-02-02 @ 06:47:31.853] [spawn] spawning isolate.exe with args --print-itch-player-details
```

Did you see an UAC prompt? Did you accept it or deny it?

**Comment by fasterthanlime** [comment]
For me: it does launch the installer, but then the installer wants to install to `C:\Program Files (x86)` which obviously won't work within the sandbox. I wish Air-based installers weren't a thing, I'm not sure how to best address this :(

**Comment by qb20nh** [comment]
I get this after disabling sandbox:
![image](https://cloud.githubusercontent.com/assets/1734074/22588077/a3db8ee6-ea47-11e6-8077-a1e3dedd8f08.png)
and I don't think this is the fault of the author

**Comment by qb20nh** [comment]
I believe this is bug from Adobe AIR.

**Comment by fasterthanlime** [comment]
> I get this after disabling sandbox:

Googling Error 5100, it might mean there's no free space in the temporary folder.

Air errors are obscure though, I tried supporting some Air games in the app a while ago and there were just so many different error conditions :(
