### ISSUE TITLE
🍎 Night in the Woods ↔ v23.2.1

### ISSUE THREAD

**Issue by sandwichpuissant** [itchio/itch-compatibility-watchlist#713]
:rotating_light: game [Night in the Woods](https://finji.itch.io/night-in-the-woods) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/de5076607b7ea73bc41c3b046a3e2155).

:running: Any additional details can go here!

: )

**Comment by fasterthanlime** [comment]
Is there a .app bundle somewhere in the install folder? (uses the "Show local files" button to see it in Finder)

**Comment by sandwichpuissant** [comment]
Not at all, in the Night in the Woods folder in my apps folder, I only have those :
https://cloud.githubusercontent.com/assets/15387138/23191377/92f57e8e-f89d-11e6-9cdc-58c1778ba9d2.png

could it be………. the windows version ? ?

itch tells me I downloaded the mac version though.

**Comment by jackl2400** [comment]
I have the same issue and am wondering the same thing (Issue #717): did itch.io somehow mislabel the Windows download as the Mac download?  

The zip file "night-in-the-woods-osx.zip" had three files, but no .dmg or .app files as you might expect for a Mac program. 

Rather it had a data folder and two files named "Night in the Woods.x86" and Night in the Woods.x86_64". The icon for those two looked like a terminal window and was labeled "Exec[utable?]".

**Comment by fasterthanlime** [comment]
> could it be………. the windows version ? ?

Nope, it was the linux version. It's all fixed now, just let the game update & you should be able to play.

**Comment by jackl2400** [comment]
Thanks!!
