### ISSUE TITLE
🍎 Night in the Woods ↔ v23.2.1

### ISSUE THREAD

**Issue by danrugh** [itchio/itch-compatibility-watchlist#714]
:rotating_light: game [Night in the Woods](https://finji.itch.io/night-in-the-woods) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6e8a5897dc848525a631d7eceb257282).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
A new build of the game is available, just let it update & you should be able to play. Sorry for the trouble!
