### ISSUE TITLE
🍎 Night in the Woods ↔ v23.2.1

### ISSUE THREAD

**Issue by samuelsleight** [itchio/itch-compatibility-watchlist#716]
:rotating_light: game [Night in the Woods](https://finji.itch.io/night-in-the-woods) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c1ccc375919895433d8ffb21f42cc85b).

:running: The game worked on first run, but not on further launch attempts. Re-installing directly did not help, and uninstalling then installing did not help either. 

The local files appear to contain no .app, which may or may not be part of the problem? 
<img width="636" alt="screen shot 2017-02-21 at 22 53 14" src="https://cloud.githubusercontent.com/assets/1221029/23188981/b2af7064-f888-11e6-9bea-f023499ce2ce.png">

**Comment by fasterthanlime** [comment]
A new build of the game is available, just let it update & you should be able to play. Sorry for the trouble!
