### ISSUE TITLE
🏁 A House of Many Doors ↔ v23.2.1

### ISSUE THREAD

**Issue by Pseudonymz** [itchio/itch-compatibility-watchlist#718]
:rotating_light: game [A House of Many Doors](https://pixeltrickery.itch.io/a-house-of-many-doors) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a28b0fe197ed82919b670b2b33ac6b1f).

:running: Itch.io DRM free version. Game started by clicking on "Launch" in itch.io client, crashes on startup but brings up Steam client pointed to homepage for A House of Many Doors. DXDiag file attached.
[DxDiag.txt](https://github.com/itchio/itch-compatibility-watchlist/files/793343/DxDiag.txt)

**Comment by fasterthanlime** [comment]
Seems like a game bug, I've pointed the developers to this thread!

**Comment by Pseudonymz** [comment]
Thanks - I agree it looks like a problem with the game.

**Comment by Skelicopter** [comment]
Try updating your DirectX at the following link (for Windows 10): https://www.microsoft.com/en-us/download/details.aspx?id=35&44F86079-8679-400C-BFF2-9CA5F2BCBDFC=1

If you're not on Windows 10, try here instead: https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=35

If that doesn't work, let me know!

**Comment by Pseudonymz** [comment]
The Windows 10 DirectX installer produced the following message:

"DirectX setup has determined that a newer or equivalent version of DirectX 
has been installed already. No installation is necessary."

and performed no actions. There was no effect on the game startup crash.


----- Original Message -----

**Comment by Skelicopter** [comment]
Okay, that's more concerning then. Could you let me know what your system specs are?

**Comment by Pseudonymz** [comment]
I've attached the DxDiag file for the system.


----- Original Message -----

**Comment by Skelicopter** [comment]
Thanks! I'm going to upload a new version of the game to Itch tonight which hopefully fixes the issue. I'll post here when it's up. After that hopefully it will be fixed, but please let me know if the issue persists.

**Comment by fasterthanlime** [comment]
@Skelicopter by the way, there's a "Debug log" link in the original comment that suggests the game is trying to relaunch itself via Steam - I thought that might be the main problem.

**Comment by Skelicopter** [comment]
@fasterthanlime Yes, I spotted this just after I posted my reply actually. (Thanks for letting me know though.)

I'm currently uploading a new version, V1.18, that hopefully fixes the issue. Please let me know!

**Comment by Pseudonymz** [comment]
After updating to the latest version using the itch.io client, the issue is 
fixed (the game starts up fine, and without bringing up the Steam client).

        Thanks!


----- Original Message -----

**Comment by Skelicopter** [comment]
Great to hear! Thanks for bringing it to my attention.

**Comment by fasterthanlime** [comment]
Awesome :star2:
