### ISSUE TITLE
🐧 Night in the Woods ↔ v23.2.1

### ISSUE THREAD

**Issue by fritzy** [itchio/itch-compatibility-watchlist#723]
:rotating_light: game [Night in the Woods](https://finji.itch.io/night-in-the-woods) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e19a12147146e435384fd5c5b63e2368).

:running: Any additional details can go here!

Just a crash on exit. Not a huge deal.

**Comment by fasterthanlime** [comment]
> Just a crash on exit. Not a huge deal.

Ah, yes, a Unity game.

Happy to see you managed to finish your download & play it :) I'm going to close this because I don't see it being fixed.

I'm pretty sure I told the itch client to ignore those errors when they happen more than a few seconds after start though, I'll take another look
