### ISSUE TITLE
🏁 GTA-V-DEMO ↔ v23.2.1

### ISSUE THREAD

**Issue by FightingMan26** [itchio/itch-compatibility-watchlist#727]
:rotating_light: game [GTA-V-DEMO](https://maurice05.itch.io/gta-v-demo) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/552f843c63ec33120c2a7ba757e5d5e1).

:running: Any additional details can go here!

**Comment by FightingMan26** [comment]
GNGH

**Comment by fasterthanlime** [comment]
flash games aren't supported in the itch.io app. sorry!
