### ISSUE TITLE
🐧 2064: Read Only Memories ↔ v23.2.1

### ISSUE THREAD

**Issue by TrollDecker** [itchio/itch-compatibility-watchlist#768]
:rotating_light: game [2064: Read Only Memories](https://midboss.itch.io/rom) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1da7730dd16bc21b06fe341ab4023e40).

:running: For all intents and purposes, the game seems to close normally when I click "Exit Game" OR the window manager's close button, just for some reason it produces an error message in the Itch app about it being killed by the signal "SIGSEGV". Sense. This makes none. o.O

**Comment by fasterthanlime** [comment]
Unity games tend to crash on exit on Linux. At some point I'll instruct the itch app to ignore that, sorry for the annoyance in the meantime :(
