### ISSUE TITLE
🏁 Breaking Character ↔ v18.0.0

### ISSUE THREAD

**Issue by codeartisticninja** [itchio/itch-compatibility-watchlist#8]
:rotating_light: game [Breaking Character](https://pierrec.itch.io/breaking-character) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2c4d17d0098dd2eccaae503767c76d0b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like that game has a separate `winsetup.exe` file that probably needs to be ran first? That's not really something the client supports at the moment.

**Comment by codeartisticninja** [comment]
Upon further inspection, it seems you just need to run `Breaking character.exe`, but the itch app wasn't able to figure that out..

**Comment by fasterthanlime** [comment]
> Upon further inspection, it seems you just need to run Breaking character.exe, but the itch app wasn't able to figure that out..

It was :)

```
[2016-07-03 @ 21:54:53.646] [launch/poker] warning: more than one candidate, picking the one with the best score
[2016-07-03 @ 21:54:53.646] [tasks/launch/native] launching 'C:\Users\bodhiBit\AppData\Roaming\itch\apps\Breaking Character\Breaking Character\Breaking character.exe' on 'win32' with args ''
```

Maybe the game is broken in the sandbox?

**Comment by codeartisticninja** [comment]
Ah yes, the game launches fine without sandbox.. However it doesn't seem to exit well..

```
Its last words were: application crashed. process exited with code 91
```

**Comment by fasterthanlime** [comment]
> However it doesn't seem to exit well..

Yeah, I'm thinking of ignoring non-zero exit codes if the game has been running for over 20 seconds or so, most games don't exist cleanly :(
