### ISSUE TITLE
🐧 Riders of Rhea ↔ v23.3.1

### ISSUE THREAD

**Issue by FESJ** [itchio/itch-compatibility-watchlist#805]
:rotating_light: game [Riders of Rhea](https://powerhoof.itch.io/riders-of-rhea) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6494acc09e97c1681d084044928e2845).

:running: Just tried to close the Game

**Comment by fasterthanlime** [comment]
Some Unity games like to crash on exit, good reminder, thanks!
