### ISSUE TITLE
🐧 Rally Racing ↔ v23.3.1

### ISSUE THREAD

**Issue by rokyed** [itchio/itch-compatibility-watchlist#806]
:rotating_light: game [Rally Racing](https://arado.itch.io/rally-racing) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1f754704978e25051d3620043328a72f).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
The game only ships with a 32-bit version, so you'll need to either install the missing libraries, or ask the developer to release a 64-bit build.
