### ISSUE TITLE
🏁 PC Building Simulator ↔ v23.3.1

### ISSUE THREAD

**Issue by bendike122** [itchio/itch-compatibility-watchlist#807]
:rotating_light: game [PC Building Simulator](https://mcintyre.itch.io/pc-building-simulator) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/4b24e13c6ffd9f925154c0d131257c25).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
You need the "x32" version of the game, not the "x64" one - uninstall & install the game again and pick the right one :)
