### ISSUE TITLE
🏁 Streets of Rogue ↔ v23.3.1

### ISSUE THREAD

**Issue by Fute200** [itchio/itch-compatibility-watchlist#808]
:rotating_light: game [Streets of Rogue](https://madguy.itch.io/streets-of-rogue) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/e86844ac5ed69b6b26b92cef91fe69eb).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
It looks like the app updated from a 32-bit version of the game to a 64-bit version. 

That's a known issue that I hope to fix soon: https://github.com/itchio/itch/issues/1129
