### ISSUE TITLE
🏁 Tiled Map Editor ↔ v18.6.1

### ISSUE THREAD

**Issue by Archeia** [itchio/itch-compatibility-watchlist#82]
:rotating_light: tool [Tiled Map Editor](https://thorbjorn.itch.io/tiled) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/15664447eafeb94054f32902ee72f3ea).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Looks like it just crashed? Doesn't seem like an app issue
