### ISSUE TITLE
🐧 The Pedestrian ↔ v23.3.1

### ISSUE THREAD

**Issue by mrmeszaros** [itchio/itch-compatibility-watchlist#822]
:rotating_light: game [The Pedestrian](https://the-pedestrian.itch.io/the-pedestrian) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/abe67a21a6aa9843d57228a82a2d944c).

:running: I was able to play the game after the second launch (also I turned down the graphics quality).

**Comment by fasterthanlime** [comment]
Ah, good to know! I'll know what to suggest to others getting a SIGSEGV :)

Closing since this is a game/driver issue, not an app issue.
