### ISSUE TITLE
🐧 Linux Gamejam 2017 ↔ v23.2.1

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch-compatibility-watchlist#826]
:rotating_light: game [Linux Gamejam 2017](https://smilex.itch.io/linux-gamejam-2017) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/7e938bba39332e185ad0129a5519e1d8).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
The download available on this page is source code, not an executable.

itch isn't able to compile stuff.. yet ;)

**Comment by aaronfranke** [comment]
Are you suggesting that Itch may be able to compile programs in the future? Perhaps running `make` etc?
