### ISSUE TITLE
🐧 Poor Man's Fly ↔ v23.3.1

### ISSUE THREAD

**Issue by aaronfranke** [itchio/itch-compatibility-watchlist#827]
:rotating_light: game [Poor Man's Fly](https://xmorg.itch.io/poor-mans-fly) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b5dc939e8a5a3e1f06b0839e3b9caab1).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Again, source code, not a binary

**Comment by aaronfranke** [comment]
Why doesn't Itch require sending a binary?

**Comment by fasterthanlime** [comment]
> Why doesn't Itch require sending a binary?

Folks create pages for a lot of stuff, some of them don't have a binary form (books, etc.).

The more interesting question imho is why do we allow people to tag "Linux, macOS, Windows" files that clearly aren't binaries, and the answer is: soon we won't anymore - tagging will be done automatically by our servers, so there won't be any more confusion possible :)

**Comment by aaronfranke** [comment]
That makes sense. Or, at least some way to make them appear to the client as un-launchable items.
