### ISSUE TITLE
🐧 Night in the Woods ↔ v23.3.1

### ISSUE THREAD

**Issue by anhinton** [itchio/itch-compatibility-watchlist#829]
:rotating_light: game [Night in the Woods](https://finji.itch.io/night-in-the-woods) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/04d4d2aa734156822f4bda35217fde95).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Crashed on exit? That happens with Unity linux games :(
