### ISSUE TITLE
🍎 Rhythm Doctor ↔ v23.3.1

### ISSUE THREAD

**Issue by as573991874** [itchio/itch-compatibility-watchlist#830]
:rotating_light: game [Rhythm Doctor](https://fizzd.itch.io/rhythm-doctor) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/aa5a383fd4d3b94ecf3b5c203b244aa0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Unfortunately the game is packaged in such a way that it's incompatible with the app.

The download contains an .swf file (the actual game) along with macOS & Windows installers for "SWF Projector", which I'm assuming lets you open .swf files on your computer.

I suggest just clicking "Show local files", and following the instructions in "HOW TO PLAY.txt".
