### ISSUE TITLE
🐧 Battlestick ↔ v23.3.1

### ISSUE THREAD

**Issue by iganev** [itchio/itch-compatibility-watchlist#831]
:rotating_light: game [Battlestick](https://pinterac.itch.io/battlestick) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b405e62e05ffd8c855ec8fa3a68952f0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
That's a web game tagged as native game. I suggest just clicking "Show local files" and opening index.html manually.

The developer can fix that with a [manifest](https://itch.io/docs/itch/integrating/manifest.html).
