### ISSUE TITLE
🐧 Bionic ↔ v23.3.1

### ISSUE THREAD

**Issue by iganev** [itchio/itch-compatibility-watchlist#832]
:rotating_light: game [Bionic](https://powerspark.itch.io/bionic) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/dd16ee9033fe2e450cf685eecd0dcc17).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Unity games tend to crash on exit on Linux.
