### ISSUE TITLE
🐧 MewnBase ↔ v23.3.1

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch-compatibility-watchlist#834]
:rotating_light: game [MewnBase](https://cairn4.itch.io/mewnbase) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/40029203318be49e2a5fb028f06c2d1d).

:running: It seems it did install though, so I'm not sure what the error was.

**Comment by fasterthanlime** [comment]
Yeah it looks like the game crapped itself:

```
[2017-03-23 @ 20:44:02.123] [launch/native] out: PostProcessor: No post-processor effects enabled, aborting render
```

better get in touch with the developers!
