### ISSUE TITLE
🏁 Fragile Soft Machines ↔ v23.4.0

### ISSUE THREAD

**Issue by omgitsraven** [itchio/itch-compatibility-watchlist#847]
:rotating_light: game [Fragile Soft Machines](https://madameberry.itch.io/fragile-soft-machines) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b4f81a19f32af0e2a7a03145abc34d89).

:running: Any additional details can go here!

Happens every time, tried uninstalling and reinstalling the game; every time it says "Error: spawn UNKNOWN". It works when I install it manually from the website.

**Comment by fasterthanlime** [comment]
That's usually because it's an unsupported installer type. The developer can repackage the game as a portable Windows archive by following instructions at https://itch.io/docs/itch/integrating/platforms/windows.html
