### ISSUE TITLE
🐧 Hyperspace Dogfights ↔ v23.4.0

### ISSUE THREAD

**Issue by LiamDawe** [itchio/itch-compatibility-watchlist#849]
:rotating_light: game [Hyperspace Dogfights](https://sleeper-games.itch.io/hyperspace-dogfights) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/98cc08c695573dbb20d0cd32539379dd).

:running: Seems to be missing a required lib? The lib is in the folder, so it's not looking for it correctly?

**Comment by fasterthanlime** [comment]
Any launcher script included with the game?

There's two ways to make the linux dynamic loader look for libraries in non-standard paths:

  * set the environment variable LD_LIBRARY_PATH (usually via a script before the game is launched)
  * set the RPATH directly into the executable (can be relative to the executable's location)

**Comment by sleeper-service-CE** [comment]
Neither me or my testers couldn't reproduce this so far, but we are all running Ubuntu (14.04 or higher). Might be Arch related?
What fasterthanlime suggested should be worth a try, the launcher script is the very "Hyperspace Dogfight" file.

**Comment by fasterthanlime** [comment]
> the launcher script is the very "Hyperspace Dogfight" file.

Does it start with `#!` ?

If not, the itch app isn't identifiying it as a potential executable target.

**Comment by sleeper-service-CE** [comment]
Oh ok wow, I wasn't really aware that the game automatically becomes available in the itch app. Can reproduce it now. That said, downloading the game from the itch site and launching it from the folder as described in the readme might work. I'm looking into making it run in the app now. Thanks so far, this was very valuable!

/Edit: Adding #! to the script or giving it the LD_LIBRARY_PATH augment did not work.
This is how the launch script looks:
```
#!
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
./ExeLinux
```
/Edit2: Running the game in terminal from inside the itch app folder works for me. Seems to be a compatibility problem with the itch app indeed.

/Edit3: Added a simple app manifest, did not help though.
```
[[actions]]
name = "play"
path = "Hyperspace Dogfights"
```

**Comment by fasterthanlime** [comment]
> /Edit: Adding #! to the script or giving it the LD_LIBRARY_PATH augment did not work.
> This is how the launch script looks:

Once the game is "configured" (ie. has been installed with the app) it doesn't look for executable targets again.

Besides, the correct script would be:

```
#!/bin/bash
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
./ExeLinux
```

I suggest pushing a build with that script. For more info about shebangs: https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by sleeper-service-CE** [comment]
Ok that didn't work either unfortunately.

**Comment by fasterthanlime** [comment]
Have you tried uninstalling/reinstalling the game ?

**Comment by fasterthanlime** [comment]
Also, whenever posting "that doesn't work", provide the log.

You can do so by right clicking on the game's tab/icon/whatever and picking 'View logs'. This lets me know what actually got launched.

**Comment by sleeper-service-CE** [comment]
Ok will do. (Uninstalling/reinstalling had no effect too)
[Here is the log.](https://gist.github.com/sleeper-service-CE/b7deef1b753d9a168d3db8aaa4907844)

**Comment by fasterthanlime** [comment]
What the app usually expects to see with respect to launcher scripts is a directory structure like:

```
root/
  launcher.sh
  binaries/
    game.x86
    game.x86_64
```

Since it prioritizes the top-most executable, `launcher.sh` would get picked here. As per the log you posted, since the launcher script and the executables are on the same level, there's no such prioritizing going on.

A manifest would indeed work around that issue but, you can see in the log as well that it didn't get picked up. You can see the exact path it tries to load it from (nb: it's `.itch.toml`, not `itch.toml`).

Care to give the manifest approach one more try? The logs are quite useful (and should be readable enough) to troubleshoot these problems, without having to wait for me to respond :)

Thanks for working on a fix! :star2:

**Comment by sleeper-service-CE** [comment]
Man I rather gotta thank you for the support. Fixing the log path indeed did it. Problem solved (at least for me on Ubuntu 14.04). Thanks for your patience. :)

**Comment by fasterthanlime** [comment]
Great!

@LiamDawe can you confirm the latest version works for you, and if it does, close this thread?

**Comment by LiamDawe** [comment]
Yep works now.

**Comment by sleeper-service-CE** [comment]
Sweet.
