### ISSUE TITLE
🏁 .defrag ↔ v23.4.0

### ISSUE THREAD

**Issue by BDash2014** [itchio/itch-compatibility-watchlist#867]
:rotating_light: game [.defrag](https://forgottendawn.itch.io/defrag) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/01174e1edb967ecc9d67e6207ed25238).

:running: Also tried running itch client with admin right, no luck

**Comment by fasterthanlime** [comment]
> tried running itch client with admin right

Thanks! That's never the solution though, please don't do that as it may cause other problems in the future :(

It looks like it's a sandbox issue, can you translate `Poadovan� operace vyaduje zv�en� opr�vnn�.` for me ?

**Comment by BDash2014** [comment]
Hi,

I tried to run itch client with admin permissions (win 10) on demand, so it’s not like I’m normally run it, no issues in the future then .

Translation is: Requesting operation requires special permission

Honza

**Comment by fasterthanlime** [comment]
If you disable the itch.io sandbox, does the game run?

**Comment by fasterthanlime** [comment]
Oh wait, I'm dumb - it's just that the game only distributes a setup file, which isn't compatible with the app.

If you want to install it manually, just click 'Show local files' and double-click on the Setup.exe

**Comment by BDash2014** [comment]
Yes, it will prolly work to install it manually, but this is why I did not install standalone version and used itch – to have game installed automatically and inside itch library, to have automatic updates etc. .

Thanks anyway,

Honza
