### ISSUE TITLE
🍎 Inspectre ↔ v23.4.0

### ISSUE THREAD

**Issue by raquelfmay2003** [itchio/itch-compatibility-watchlist#869]
:rotating_light: game [Inspectre](https://aethericgames.itch.io/inspectre) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a1620c8b94a367e6cd165e3c846620e9).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
That's a flash game, those wil unfortunately never be supported in the app.
