### ISSUE TITLE
🏁 Bad Bots Rises ↔ v23.4.0

### ISSUE THREAD

**Issue by FilthySilver** [itchio/itch-compatibility-watchlist#871]
:rotating_light: game [Bad Bots Rises](https://digital-adobo.itch.io/badbotsrises) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9289ba28d95f67e9c49f00c4e39c59fc).

:running: Any additional details can go here!

![Uploading image.png…]()

I tried launching every games I got installed on Itch and they keep giving me the message: "application crashed. process exited with code 127".
I even reinstalled one game and still got the same message.

**Comment by fasterthanlime** [comment]
Try unchecking `itch.io sandbox` in the preference, that'll work.

Would you be willing to run a few commands on your system to help find where the sandbox problem comes from ?

**Comment by FilthySilver** [comment]
It worked, thanks.
