### ISSUE TITLE
🏁 Don't Bite Me Bro! ↔ v23.4.0

### ISSUE THREAD

**Issue by SergeySch** [itchio/itch-compatibility-watchlist#878]
:rotating_light: game [Don't Bite Me Bro!](https://muifwego.itch.io/dont-bite-me-bro) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/11e78554304751721d14c3c960d19e8f).

:running: Tried to run in sandbox mode

**Comment by fasterthanlime** [comment]
Looks like an unsupported installer format, the developers of the game should fix that

**Comment by fasterthanlime** [comment]
Looks like the developers are using butler to push the game now :)
