### ISSUE TITLE
🏁 Tiled Map Editor ↔ v23.4.0

### ISSUE THREAD

**Issue by edderiofer** [itchio/itch-compatibility-watchlist#879]
:rotating_light: tool [Tiled Map Editor](https://thorbjorn.itch.io/tiled) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c5891b7d9091ea4ded87ee7c6d39f5bb).

:running: Specifically, I tried installing it; it downloaded but perpetually got stuck at Installing (0%ish). I restarted itch.io, and the game was marked as "installed". Trying to uninstall it doesn't do so; trying to reinstall it results in the same problem.

**Comment by fasterthanlime** [comment]
If you go to the Control Panel => Add & Remove Programs, is there a Tiled in there?

**Comment by edderiofer** [comment]
I've since installed Tiled manually outside of the itch.io client, so I can't tell what the answer would be. However, I definitely recall seeing no such Tiled folder in the place where itch.io installs games to.

**Comment by fasterthanlime** [comment]
> I've since installed Tiled manually outside of the itch.io client, so I can't tell what the answer would be. However, I definitely recall seeing no such Tiled folder in the place where itch.io installs games to.

Yep. The thing with Tiled is that it ships an MSI file (a Microsoft Installer package) - those can be sometimes finicky. The app tries to install them with msiexec, giving them the right install location, but there are many possible error conditions for MSI installers, and their logs are almost impossible to parser.

Tiled being already installed outside the app would definitely be a reason for the MSI install to fail - although the app would normally attempt to detect that (but it's possible that the MSI install failed for a slightly different reason...).

I really wish MSIs weren't a thing, but they are :(
