### ISSUE TITLE
🏁 ALONE ↔ v23.4.0

### ISSUE THREAD

**Issue by NexSqaud** [itchio/itch-compatibility-watchlist#897]
:rotating_light: game [ALONE](https://jdizzle144.itch.io/alone) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/1b39497b04b978abc180d0caed406fbf).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
As said in the commentes of the game - that's a mac release, not windows.
