### ISSUE TITLE
🐧 Wasteland Kings Together ↔ v18.0.0

### ISSUE THREAD

**Issue by hellscyth142** [itchio/itch-compatibility-watchlist#9]
:rotating_light: game [Wasteland Kings Together](https://yellowafterlife.itch.io/wasteland-kings-together) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d5489af4adc99d0b649e73476ab7b21a).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
You're missing libcurl, as the log says :)

Also, the game is not properly packaged — it should ship with dependencies like that, https://itch.io/docs/itch/integrating/platforms/linux.html

**Comment by hellscyth142** [comment]
I'm trying to get libcurl (on mint 18), but I'm running into a lot of no installation candidate. Thanks for the advice. Expect to see a few of these crop up, we're making a reddit megathread of indie games, and there is a lot of itch.io stuff.

**Comment by fasterthanlime** [comment]
> Expect to see a few of these crop up, we're making a reddit megathread of indie games, and there is a lot of itch.io stuff.

👍 sounds good! I'm happy to help.

> I'm trying to get libcurl (on mint 18), but I'm running into a lot of no installation candidate.

I fully empathize with being stuck in debian packaging hell :( maybe it'd be easier to get YellowAfterLife to ship libcurl.so directly with the game?

**Comment by YellowAfterlife** [comment]
Full dependency list is

```
libc6-dev-i386
libstdc++6:i386
libopenal1:i386
libxxf86vm1:i386
libglu1:i386
libcurl3:i386
libxrandr2:i386
```

(I've detailed a bunch of things in a [post on Reddit](https://www.reddit.com/r/linux_gaming/comments/4e7fa0/sp_dont_crawl_and_other_small_games_with_online/))

I've been considering shipping full dependencies with games, but in total these occupy more space than actual games on average do, so it'd be a shame to have the user download this with each of them.

**Comment by fasterthanlime** [comment]
> I've been considering shipping full dependencies with games, but in total these occupy more space than actual games on average do, so it'd be a shame to have the user download this with each of them.

@YellowAfterlife I strongly advise to follow this advice:
- https://itch.io/docs/itch/integrating/platforms/linux.html
- https://gist.github.com/flibitijibibo/b67910842ab95bb3decdf89d1502de88

Dynamic libraries generally compress really well. In my view, compatibility wins over download size every time, but if you're really worried about it, why not keep the "dependency-less" build on the itch.io page, but further down the list, so that the app doesn't pick it up?
