### ISSUE TITLE
🍎 CraftStudio ↔ v23.4.0

### ISSUE THREAD

**Issue by burakerk** [itchio/itch-compatibility-watchlist#906]
:rotating_light: game [CraftStudio](https://sparklinlabs.itch.io/craftstudio) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/94ce34c863fd837d1ca05f7e6ea6d874).

:running: Any additional details can go here!

**Comment by NexSqaud** [comment]
itch not found a executable file. Try to reload again

**Comment by fasterthanlime** [comment]
Nah, it won't work. CraftStudio is a .pkg file, it's an installer kind for macOS that the itch app doesn't support.

The developers of CraftStudio are aware of that but aren't going to update it since they've discontinued work on it, so, sorry :(
