### ISSUE TITLE
🐧 Bullet Hell ↔ v23.4.1

### ISSUE THREAD

**Issue by ghost** [itchio/itch-compatibility-watchlist#928]
:rotating_light: game [Bullet Hell](https://caiomga.itch.io/bullet-hell) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/29fb5db2b937db677dc12984b46f29b8).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
That's an HTML game tagged as if it were a native Linux game. The developer can fix this with an [app manifest](https://itch.io/docs/itch/integrating/manifest.html), you can play it just by clicking 'Show local files', and double-clicking 'index.html' so it opens in your browser.

**Comment by ghost** [comment]
oh i see, sorry didn't realize

**Comment by fasterthanlime** [comment]
No sweat! It's a common problem, unfortunately. Future versions of the itch app should handle those games better :)
