### ISSUE TITLE
🏁 Where Is My Hammer: Destroy Everything! ↔ v18.6.1

### ISSUE THREAD

**Issue by Shaggy91** [itchio/itch-compatibility-watchlist#93]
:rotating_light: game [Where Is My Hammer: Destroy Everything!](https://tocogames.itch.io/where-is-my-hammer-destroy-everything) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2f767ea220d81f488ca69d94145d6f2d).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Same issue as #91
