### ISSUE TITLE
🍎 ChemCaper Act 1: Petticles in Peril ↔ v23.4.1

### ISSUE THREAD

**Issue by NickRitson** [itchio/itch-compatibility-watchlist#950]
:rotating_light: game [ChemCaper Act 1: Petticles in Peril](https://ace-ed-venture-studio.itch.io/chemcaper-act-1-petticles-in-peril) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cfdc95892a3ad7334a5f1a1a47813212).

:running: Any additional details can go here!
just opened the itch launcher and clicked the launch button on the game

**Comment by fasterthanlime** [comment]
That's a .pkg - ie. a macOS installer. The app doesn't know what to do with those, so I'm afraid you'll have to install it by hand.

Since it's already been downloaded by the app, you can find it in `~/Library/Application Support/itch/downloads/ChemCaper_MacOS.pkg`
