### ISSUE TITLE
🏁 Disorient On The Murder Express ↔ v23.4.1

### ISSUE THREAD

**Issue by DancingEngie** [itchio/itch-compatibility-watchlist#971]
:rotating_light: game [Disorient On The Murder Express](https://nationalinsecurities.itch.io/disorient-on-the-murder-express) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/83c7e4d669d0c92155524379c8ee836d).

:running: This is weird as the itch app correctly identified that this game is a UE4 engine game and installed some prequisits. The same _"spawn icacls ENOENT"_ error occurs when trying to launch Unity games as well.

**Comment by fasterthanlime** [comment]
Huh, that's the first time I see a windows install missing both "wmic" and "icacls"

Do you not have a "wmic.exe" file in `C:\Windows\system32\wbem` and a "icacls.exe" file in `C:\Windows\system32` ?

Also, if you start a `cmd.exe` (Command line prompt), can you send me a screenshot of what it says after typing `echo %PATH%` and pressing enter?

**Comment by DancingEngie** [comment]
@fasterthanlime 
I do have both of these files. As for the command line prompt:
![2017-06-03 12_01_52- disorient on the murder express v23 4 1 issue 971 itchio_itch-compatib](https://cloud.githubusercontent.com/assets/9748479/26752263/876cdf60-4854-11e7-9ca4-b9b35b530a11.png)

**Comment by fasterthanlime** [comment]
Ah, well, there's your problem :) Your %PATH% should contain `C:\Windows\System32` and `C:\Windows\System32\wbem`, here's what mine looks like:

![correct-path](https://cloud.githubusercontent.com/assets/7998310/26752507/03ef9472-4852-11e7-89ec-41711afa8466.png)

You can fix your PATH through Control Panel -> System -> Edit Environment variables for your account. (That's probably how it was changed in the first place!)

You'll have to quit & start the itch app again after adjusting your PATH.

**Comment by DancingEngie** [comment]
Damn Dashline. Thanks Amos, continue your wonderful work in itch :)
