### ISSUE TITLE
🏁 Exodemon ↔ v18.6.1

### ISSUE THREAD

**Issue by dampayoub** [itchio/itch-compatibility-watchlist#99]
:rotating_light: game [Exodemon](https://kuupu.itch.io/exodemon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/38be4c4af7055b6774234f8e0585fafa).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment]
Exodemon is a 64-bit game, so it won't run on your 32-bit windows :(
